note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class ADDRESS




feature --Access

    city: detachable STRING_32
      
    company: detachable STRING_32
      
    country: detachable STRING_32
      -- ISO 3166-1 alpha-2 country code (e.g. \"DE\", \"PL\", \"FR\").
    email: detachable STRING_32
      
    name: detachable STRING_32
      
    phone: detachable STRING_32
      
    street: detachable STRING_32
      
    street_number: detachable STRING_32
      
    zip: detachable STRING_32
      

feature -- Change Element

    set_city (a_name: like city)
        -- Set 'city' with 'a_name'.
      do
        city := a_name
      ensure
        city_set: city = a_name
      end

    set_company (a_name: like company)
        -- Set 'company' with 'a_name'.
      do
        company := a_name
      ensure
        company_set: company = a_name
      end

    set_country (a_name: like country)
        -- Set 'country' with 'a_name'.
      do
        country := a_name
      ensure
        country_set: country = a_name
      end

    set_email (a_name: like email)
        -- Set 'email' with 'a_name'.
      do
        email := a_name
      ensure
        email_set: email = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end

    set_phone (a_name: like phone)
        -- Set 'phone' with 'a_name'.
      do
        phone := a_name
      ensure
        phone_set: phone = a_name
      end

    set_street (a_name: like street)
        -- Set 'street' with 'a_name'.
      do
        street := a_name
      ensure
        street_set: street = a_name
      end

    set_street_number (a_name: like street_number)
        -- Set 'street_number' with 'a_name'.
      do
        street_number := a_name
      ensure
        street_number_set: street_number = a_name
      end

    set_zip (a_name: like zip)
        -- Set 'zip' with 'a_name'.
      do
        zip := a_name
      ensure
        zip_set: zip = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass ADDRESS%N")
        if attached city as l_city then
          Result.append ("%Ncity:")
          Result.append (l_city.out)
          Result.append ("%N")
        end
        if attached company as l_company then
          Result.append ("%Ncompany:")
          Result.append (l_company.out)
          Result.append ("%N")
        end
        if attached country as l_country then
          Result.append ("%Ncountry:")
          Result.append (l_country.out)
          Result.append ("%N")
        end
        if attached email as l_email then
          Result.append ("%Nemail:")
          Result.append (l_email.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
        if attached phone as l_phone then
          Result.append ("%Nphone:")
          Result.append (l_phone.out)
          Result.append ("%N")
        end
        if attached street as l_street then
          Result.append ("%Nstreet:")
          Result.append (l_street.out)
          Result.append ("%N")
        end
        if attached street_number as l_street_number then
          Result.append ("%Nstreet_number:")
          Result.append (l_street_number.out)
          Result.append ("%N")
        end
        if attached zip as l_zip then
          Result.append ("%Nzip:")
          Result.append (l_zip.out)
          Result.append ("%N")
        end
      end
end

