note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class AI_SUGGESTION




feature --Access

    confidence: REAL_64
      
    reasoning: detachable STRING_32
      
    suggested_priority: detachable STRING_32
      
    suggested_reply: detachable STRING_32
      
    suggested_status: detachable STRING_32
      
    tool_calls: detachable LIST [STRING_32]
      

feature -- Change Element

    set_confidence (a_name: like confidence)
        -- Set 'confidence' with 'a_name'.
      do
        confidence := a_name
      ensure
        confidence_set: confidence = a_name
      end

    set_reasoning (a_name: like reasoning)
        -- Set 'reasoning' with 'a_name'.
      do
        reasoning := a_name
      ensure
        reasoning_set: reasoning = a_name
      end

    set_suggested_priority (a_name: like suggested_priority)
        -- Set 'suggested_priority' with 'a_name'.
      do
        suggested_priority := a_name
      ensure
        suggested_priority_set: suggested_priority = a_name
      end

    set_suggested_reply (a_name: like suggested_reply)
        -- Set 'suggested_reply' with 'a_name'.
      do
        suggested_reply := a_name
      ensure
        suggested_reply_set: suggested_reply = a_name
      end

    set_suggested_status (a_name: like suggested_status)
        -- Set 'suggested_status' with 'a_name'.
      do
        suggested_status := a_name
      ensure
        suggested_status_set: suggested_status = a_name
      end

    set_tool_calls (a_name: like tool_calls)
        -- Set 'tool_calls' with 'a_name'.
      do
        tool_calls := a_name
      ensure
        tool_calls_set: tool_calls = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass AI_SUGGESTION%N")
        if attached confidence as l_confidence then
          Result.append ("%Nconfidence:")
          Result.append (l_confidence.out)
          Result.append ("%N")
        end
        if attached reasoning as l_reasoning then
          Result.append ("%Nreasoning:")
          Result.append (l_reasoning.out)
          Result.append ("%N")
        end
        if attached suggested_priority as l_suggested_priority then
          Result.append ("%Nsuggested_priority:")
          Result.append (l_suggested_priority.out)
          Result.append ("%N")
        end
        if attached suggested_reply as l_suggested_reply then
          Result.append ("%Nsuggested_reply:")
          Result.append (l_suggested_reply.out)
          Result.append ("%N")
        end
        if attached suggested_status as l_suggested_status then
          Result.append ("%Nsuggested_status:")
          Result.append (l_suggested_status.out)
          Result.append ("%N")
        end
        if attached tool_calls as l_tool_calls then
          across l_tool_calls as ic loop
            Result.append ("%N tool_calls:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
      end
end

