note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class ATTACHMENT




feature --Access

    contact_id: detachable STRING_32
      -- Contact this attachment belongs to (per-contact DMS). References the contact entity.
    file_name: detachable STRING_32
      
    file_size: INTEGER_64
      
    mime_type: detachable STRING_32
      
    ocr_text: detachable STRING_32
      -- Raw text extracted by client-side OCR (tesseract.js), if run.
    original_name: detachable STRING_32
      
    pdfa_path: detachable STRING_32
      
    sha256_hash: detachable STRING_32
      
    uploaded_by: detachable UUID
      

feature -- Change Element

    set_contact_id (a_name: like contact_id)
        -- Set 'contact_id' with 'a_name'.
      do
        contact_id := a_name
      ensure
        contact_id_set: contact_id = a_name
      end

    set_file_name (a_name: like file_name)
        -- Set 'file_name' with 'a_name'.
      do
        file_name := a_name
      ensure
        file_name_set: file_name = a_name
      end

    set_file_size (a_name: like file_size)
        -- Set 'file_size' with 'a_name'.
      do
        file_size := a_name
      ensure
        file_size_set: file_size = a_name
      end

    set_mime_type (a_name: like mime_type)
        -- Set 'mime_type' with 'a_name'.
      do
        mime_type := a_name
      ensure
        mime_type_set: mime_type = a_name
      end

    set_ocr_text (a_name: like ocr_text)
        -- Set 'ocr_text' with 'a_name'.
      do
        ocr_text := a_name
      ensure
        ocr_text_set: ocr_text = a_name
      end

    set_original_name (a_name: like original_name)
        -- Set 'original_name' with 'a_name'.
      do
        original_name := a_name
      ensure
        original_name_set: original_name = a_name
      end

    set_pdfa_path (a_name: like pdfa_path)
        -- Set 'pdfa_path' with 'a_name'.
      do
        pdfa_path := a_name
      ensure
        pdfa_path_set: pdfa_path = a_name
      end

    set_sha256_hash (a_name: like sha256_hash)
        -- Set 'sha256_hash' with 'a_name'.
      do
        sha256_hash := a_name
      ensure
        sha256_hash_set: sha256_hash = a_name
      end

    set_uploaded_by (a_name: like uploaded_by)
        -- Set 'uploaded_by' with 'a_name'.
      do
        uploaded_by := a_name
      ensure
        uploaded_by_set: uploaded_by = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass ATTACHMENT%N")
        if attached contact_id as l_contact_id then
          Result.append ("%Ncontact_id:")
          Result.append (l_contact_id.out)
          Result.append ("%N")
        end
        if attached file_name as l_file_name then
          Result.append ("%Nfile_name:")
          Result.append (l_file_name.out)
          Result.append ("%N")
        end
        if attached file_size as l_file_size then
          Result.append ("%Nfile_size:")
          Result.append (l_file_size.out)
          Result.append ("%N")
        end
        if attached mime_type as l_mime_type then
          Result.append ("%Nmime_type:")
          Result.append (l_mime_type.out)
          Result.append ("%N")
        end
        if attached ocr_text as l_ocr_text then
          Result.append ("%Nocr_text:")
          Result.append (l_ocr_text.out)
          Result.append ("%N")
        end
        if attached original_name as l_original_name then
          Result.append ("%Noriginal_name:")
          Result.append (l_original_name.out)
          Result.append ("%N")
        end
        if attached pdfa_path as l_pdfa_path then
          Result.append ("%Npdfa_path:")
          Result.append (l_pdfa_path.out)
          Result.append ("%N")
        end
        if attached sha256_hash as l_sha256_hash then
          Result.append ("%Nsha256_hash:")
          Result.append (l_sha256_hash.out)
          Result.append ("%N")
        end
        if attached uploaded_by as l_uploaded_by then
          Result.append ("%Nuploaded_by:")
          Result.append (l_uploaded_by.out)
          Result.append ("%N")
        end
      end
end

