note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class ATTACHMENT_VERSION




feature --Access

    attachment_id: detachable UUID
      -- Parent attachment whose history this row records.
    file_name: detachable STRING_32
      -- Storage key of this version's bytes.
    file_size: INTEGER_64
      
    mime_type: detachable STRING_32
      
    original_name: detachable STRING_32
      
    sha256_hash: detachable STRING_32
      
    uploaded_by: detachable UUID
      
    version_number: INTEGER_32
      -- 1-based; ascending per attachment in upload order.

feature -- Change Element

    set_attachment_id (a_name: like attachment_id)
        -- Set 'attachment_id' with 'a_name'.
      do
        attachment_id := a_name
      ensure
        attachment_id_set: attachment_id = a_name
      end

    set_file_name (a_name: like file_name)
        -- Set 'file_name' with 'a_name'.
      do
        file_name := a_name
      ensure
        file_name_set: file_name = a_name
      end

    set_file_size (a_name: like file_size)
        -- Set 'file_size' with 'a_name'.
      do
        file_size := a_name
      ensure
        file_size_set: file_size = a_name
      end

    set_mime_type (a_name: like mime_type)
        -- Set 'mime_type' with 'a_name'.
      do
        mime_type := a_name
      ensure
        mime_type_set: mime_type = a_name
      end

    set_original_name (a_name: like original_name)
        -- Set 'original_name' with 'a_name'.
      do
        original_name := a_name
      ensure
        original_name_set: original_name = a_name
      end

    set_sha256_hash (a_name: like sha256_hash)
        -- Set 'sha256_hash' with 'a_name'.
      do
        sha256_hash := a_name
      ensure
        sha256_hash_set: sha256_hash = a_name
      end

    set_uploaded_by (a_name: like uploaded_by)
        -- Set 'uploaded_by' with 'a_name'.
      do
        uploaded_by := a_name
      ensure
        uploaded_by_set: uploaded_by = a_name
      end

    set_version_number (a_name: like version_number)
        -- Set 'version_number' with 'a_name'.
      do
        version_number := a_name
      ensure
        version_number_set: version_number = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass ATTACHMENT_VERSION%N")
        if attached attachment_id as l_attachment_id then
          Result.append ("%Nattachment_id:")
          Result.append (l_attachment_id.out)
          Result.append ("%N")
        end
        if attached file_name as l_file_name then
          Result.append ("%Nfile_name:")
          Result.append (l_file_name.out)
          Result.append ("%N")
        end
        if attached file_size as l_file_size then
          Result.append ("%Nfile_size:")
          Result.append (l_file_size.out)
          Result.append ("%N")
        end
        if attached mime_type as l_mime_type then
          Result.append ("%Nmime_type:")
          Result.append (l_mime_type.out)
          Result.append ("%N")
        end
        if attached original_name as l_original_name then
          Result.append ("%Noriginal_name:")
          Result.append (l_original_name.out)
          Result.append ("%N")
        end
        if attached sha256_hash as l_sha256_hash then
          Result.append ("%Nsha256_hash:")
          Result.append (l_sha256_hash.out)
          Result.append ("%N")
        end
        if attached uploaded_by as l_uploaded_by then
          Result.append ("%Nuploaded_by:")
          Result.append (l_uploaded_by.out)
          Result.append ("%N")
        end
        if attached version_number as l_version_number then
          Result.append ("%Nversion_number:")
          Result.append (l_version_number.out)
          Result.append ("%N")
        end
      end
end

