note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class AUTOMATION_DTO




feature --Access

    automation_key: detachable STRING_32
      
    config: detachable ANY
      
    default_day: INTEGER_32
      
    description: detachable STRING_32
      
    enabled: BOOLEAN
      
    kind: detachable STRING_32
      
    last_run_at: detachable DATE_TIME
      
    next_run_at: detachable DATE_TIME
      
    schedule_kind: detachable STRING_32
      

feature -- Change Element

    set_automation_key (a_name: like automation_key)
        -- Set 'automation_key' with 'a_name'.
      do
        automation_key := a_name
      ensure
        automation_key_set: automation_key = a_name
      end

    set_config (a_name: like config)
        -- Set 'config' with 'a_name'.
      do
        config := a_name
      ensure
        config_set: config = a_name
      end

    set_default_day (a_name: like default_day)
        -- Set 'default_day' with 'a_name'.
      do
        default_day := a_name
      ensure
        default_day_set: default_day = a_name
      end

    set_description (a_name: like description)
        -- Set 'description' with 'a_name'.
      do
        description := a_name
      ensure
        description_set: description = a_name
      end

    set_enabled (a_name: like enabled)
        -- Set 'enabled' with 'a_name'.
      do
        enabled := a_name
      ensure
        enabled_set: enabled = a_name
      end

    set_kind (a_name: like kind)
        -- Set 'kind' with 'a_name'.
      do
        kind := a_name
      ensure
        kind_set: kind = a_name
      end

    set_last_run_at (a_name: like last_run_at)
        -- Set 'last_run_at' with 'a_name'.
      do
        last_run_at := a_name
      ensure
        last_run_at_set: last_run_at = a_name
      end

    set_next_run_at (a_name: like next_run_at)
        -- Set 'next_run_at' with 'a_name'.
      do
        next_run_at := a_name
      ensure
        next_run_at_set: next_run_at = a_name
      end

    set_schedule_kind (a_name: like schedule_kind)
        -- Set 'schedule_kind' with 'a_name'.
      do
        schedule_kind := a_name
      ensure
        schedule_kind_set: schedule_kind = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass AUTOMATION_DTO%N")
        if attached automation_key as l_automation_key then
          Result.append ("%Nautomation_key:")
          Result.append (l_automation_key.out)
          Result.append ("%N")
        end
        if attached config as l_config then
          Result.append ("%Nconfig:")
          Result.append (l_config.out)
          Result.append ("%N")
        end
        if attached default_day as l_default_day then
          Result.append ("%Ndefault_day:")
          Result.append (l_default_day.out)
          Result.append ("%N")
        end
        if attached description as l_description then
          Result.append ("%Ndescription:")
          Result.append (l_description.out)
          Result.append ("%N")
        end
        if attached enabled as l_enabled then
          Result.append ("%Nenabled:")
          Result.append (l_enabled.out)
          Result.append ("%N")
        end
        if attached kind as l_kind then
          Result.append ("%Nkind:")
          Result.append (l_kind.out)
          Result.append ("%N")
        end
        if attached last_run_at as l_last_run_at then
          Result.append ("%Nlast_run_at:")
          Result.append (l_last_run_at.out)
          Result.append ("%N")
        end
        if attached next_run_at as l_next_run_at then
          Result.append ("%Nnext_run_at:")
          Result.append (l_next_run_at.out)
          Result.append ("%N")
        end
        if attached schedule_kind as l_schedule_kind then
          Result.append ("%Nschedule_kind:")
          Result.append (l_schedule_kind.out)
          Result.append ("%N")
        end
      end
end

