note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class BALANCE_SHEET




feature --Access

    assets: detachable LIST [BALANCE_ITEM]
      
    balanced: BOOLEAN
      
    equity_liabilities: detachable LIST [BALANCE_ITEM]
      
    total_assets: detachable STRING_32
      
    total_equity_liabilities: detachable STRING_32
      

feature -- Change Element

    set_assets (a_name: like assets)
        -- Set 'assets' with 'a_name'.
      do
        assets := a_name
      ensure
        assets_set: assets = a_name
      end

    set_balanced (a_name: like balanced)
        -- Set 'balanced' with 'a_name'.
      do
        balanced := a_name
      ensure
        balanced_set: balanced = a_name
      end

    set_equity_liabilities (a_name: like equity_liabilities)
        -- Set 'equity_liabilities' with 'a_name'.
      do
        equity_liabilities := a_name
      ensure
        equity_liabilities_set: equity_liabilities = a_name
      end

    set_total_assets (a_name: like total_assets)
        -- Set 'total_assets' with 'a_name'.
      do
        total_assets := a_name
      ensure
        total_assets_set: total_assets = a_name
      end

    set_total_equity_liabilities (a_name: like total_equity_liabilities)
        -- Set 'total_equity_liabilities' with 'a_name'.
      do
        total_equity_liabilities := a_name
      ensure
        total_equity_liabilities_set: total_equity_liabilities = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass BALANCE_SHEET%N")
        if attached assets as l_assets then
          across l_assets as ic loop
            Result.append ("%N assets:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached balanced as l_balanced then
          Result.append ("%Nbalanced:")
          Result.append (l_balanced.out)
          Result.append ("%N")
        end
        if attached equity_liabilities as l_equity_liabilities then
          across l_equity_liabilities as ic loop
            Result.append ("%N equity_liabilities:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_assets as l_total_assets then
          Result.append ("%Ntotal_assets:")
          Result.append (l_total_assets.out)
          Result.append ("%N")
        end
        if attached total_equity_liabilities as l_total_equity_liabilities then
          Result.append ("%Ntotal_equity_liabilities:")
          Result.append (l_total_equity_liabilities.out)
          Result.append ("%N")
        end
      end
end

