note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class BUDGET_ERGEBNIS




feature --Access

    jahr: INTEGER_32
      
    monat: INTEGER_32
      
    monats_budget: detachable LIST [BUDGET_KATEGORIE]
      
    prognose_restjahr: detachable LIST [BUDGET_KATEGORIE]
      

feature -- Change Element

    set_jahr (a_name: like jahr)
        -- Set 'jahr' with 'a_name'.
      do
        jahr := a_name
      ensure
        jahr_set: jahr = a_name
      end

    set_monat (a_name: like monat)
        -- Set 'monat' with 'a_name'.
      do
        monat := a_name
      ensure
        monat_set: monat = a_name
      end

    set_monats_budget (a_name: like monats_budget)
        -- Set 'monats_budget' with 'a_name'.
      do
        monats_budget := a_name
      ensure
        monats_budget_set: monats_budget = a_name
      end

    set_prognose_restjahr (a_name: like prognose_restjahr)
        -- Set 'prognose_restjahr' with 'a_name'.
      do
        prognose_restjahr := a_name
      ensure
        prognose_restjahr_set: prognose_restjahr = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass BUDGET_ERGEBNIS%N")
        if attached jahr as l_jahr then
          Result.append ("%Njahr:")
          Result.append (l_jahr.out)
          Result.append ("%N")
        end
        if attached monat as l_monat then
          Result.append ("%Nmonat:")
          Result.append (l_monat.out)
          Result.append ("%N")
        end
        if attached monats_budget as l_monats_budget then
          across l_monats_budget as ic loop
            Result.append ("%N monats_budget:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached prognose_restjahr as l_prognose_restjahr then
          across l_prognose_restjahr as ic loop
            Result.append ("%N prognose_restjahr:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
      end
end

