note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class BWA_REVENUE




feature --Access

    revenue_breakdown: detachable LIST [REVENUE_ITEM]
      
    total_revenue: detachable STRING_32
      

feature -- Change Element

    set_revenue_breakdown (a_name: like revenue_breakdown)
        -- Set 'revenue_breakdown' with 'a_name'.
      do
        revenue_breakdown := a_name
      ensure
        revenue_breakdown_set: revenue_breakdown = a_name
      end

    set_total_revenue (a_name: like total_revenue)
        -- Set 'total_revenue' with 'a_name'.
      do
        total_revenue := a_name
      ensure
        total_revenue_set: total_revenue = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass BWA_REVENUE%N")
        if attached revenue_breakdown as l_revenue_breakdown then
          across l_revenue_breakdown as ic loop
            Result.append ("%N revenue_breakdown:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_revenue as l_total_revenue then
          Result.append ("%Ntotal_revenue:")
          Result.append (l_total_revenue.out)
          Result.append ("%N")
        end
      end
end

