note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CATEGORY_TOTAL




feature --Access

    category_id: detachable STRING_32
      
    share_pct: REAL_64
      
    tco2e: detachable STRING_32
      

feature -- Change Element

    set_category_id (a_name: like category_id)
        -- Set 'category_id' with 'a_name'.
      do
        category_id := a_name
      ensure
        category_id_set: category_id = a_name
      end

    set_share_pct (a_name: like share_pct)
        -- Set 'share_pct' with 'a_name'.
      do
        share_pct := a_name
      ensure
        share_pct_set: share_pct = a_name
      end

    set_tco2e (a_name: like tco2e)
        -- Set 'tco2e' with 'a_name'.
      do
        tco2e := a_name
      ensure
        tco2e_set: tco2e = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CATEGORY_TOTAL%N")
        if attached category_id as l_category_id then
          Result.append ("%Ncategory_id:")
          Result.append (l_category_id.out)
          Result.append ("%N")
        end
        if attached share_pct as l_share_pct then
          Result.append ("%Nshare_pct:")
          Result.append (l_share_pct.out)
          Result.append ("%N")
        end
        if attached tco2e as l_tco2e then
          Result.append ("%Ntco2e:")
          Result.append (l_tco2e.out)
          Result.append ("%N")
        end
      end
end

