note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class COMPLIANCE_TRAINING_UPDATE




feature --Access

    assignable: BOOLEAN
      -- Whether HR can assign this training as required for employees.
    code: detachable STRING_32
      -- Stable code used by plugins and frontend players (e.g. \"data_privacy\").
    description: detachable STRING_32
      
    pass_score: INTEGER_32
      -- Minimum score (0–100) required to pass.
    plugin_platform: detachable STRING_32
      -- Marketplace plugin platform id when source = Plugin.
    source: detachable TRAINING_SOURCE
      
    title: detachable STRING_32
      
    validity_months: INTEGER_32
      -- Certificate validity in months; null = no expiry.

feature -- Change Element

    set_assignable (a_name: like assignable)
        -- Set 'assignable' with 'a_name'.
      do
        assignable := a_name
      ensure
        assignable_set: assignable = a_name
      end

    set_code (a_name: like code)
        -- Set 'code' with 'a_name'.
      do
        code := a_name
      ensure
        code_set: code = a_name
      end

    set_description (a_name: like description)
        -- Set 'description' with 'a_name'.
      do
        description := a_name
      ensure
        description_set: description = a_name
      end

    set_pass_score (a_name: like pass_score)
        -- Set 'pass_score' with 'a_name'.
      do
        pass_score := a_name
      ensure
        pass_score_set: pass_score = a_name
      end

    set_plugin_platform (a_name: like plugin_platform)
        -- Set 'plugin_platform' with 'a_name'.
      do
        plugin_platform := a_name
      ensure
        plugin_platform_set: plugin_platform = a_name
      end

    set_source (a_name: like source)
        -- Set 'source' with 'a_name'.
      do
        source := a_name
      ensure
        source_set: source = a_name
      end

    set_title (a_name: like title)
        -- Set 'title' with 'a_name'.
      do
        title := a_name
      ensure
        title_set: title = a_name
      end

    set_validity_months (a_name: like validity_months)
        -- Set 'validity_months' with 'a_name'.
      do
        validity_months := a_name
      ensure
        validity_months_set: validity_months = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass COMPLIANCE_TRAINING_UPDATE%N")
        if attached assignable as l_assignable then
          Result.append ("%Nassignable:")
          Result.append (l_assignable.out)
          Result.append ("%N")
        end
        if attached code as l_code then
          Result.append ("%Ncode:")
          Result.append (l_code.out)
          Result.append ("%N")
        end
        if attached description as l_description then
          Result.append ("%Ndescription:")
          Result.append (l_description.out)
          Result.append ("%N")
        end
        if attached pass_score as l_pass_score then
          Result.append ("%Npass_score:")
          Result.append (l_pass_score.out)
          Result.append ("%N")
        end
        if attached plugin_platform as l_plugin_platform then
          Result.append ("%Nplugin_platform:")
          Result.append (l_plugin_platform.out)
          Result.append ("%N")
        end
        if attached source as l_source then
          Result.append ("%Nsource:")
          Result.append (l_source.out)
          Result.append ("%N")
        end
        if attached title as l_title then
          Result.append ("%Ntitle:")
          Result.append (l_title.out)
          Result.append ("%N")
        end
        if attached validity_months as l_validity_months then
          Result.append ("%Nvalidity_months:")
          Result.append (l_validity_months.out)
          Result.append ("%N")
        end
      end
end

