note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CONTACT_INFO




feature --Access

    hint: detachable STRING_32
      
    hint_en: detachable STRING_32
      
    role: detachable STRING_32
      
    role_en: detachable STRING_32
      

feature -- Change Element

    set_hint (a_name: like hint)
        -- Set 'hint' with 'a_name'.
      do
        hint := a_name
      ensure
        hint_set: hint = a_name
      end

    set_hint_en (a_name: like hint_en)
        -- Set 'hint_en' with 'a_name'.
      do
        hint_en := a_name
      ensure
        hint_en_set: hint_en = a_name
      end

    set_role (a_name: like role)
        -- Set 'role' with 'a_name'.
      do
        role := a_name
      ensure
        role_set: role = a_name
      end

    set_role_en (a_name: like role_en)
        -- Set 'role_en' with 'a_name'.
      do
        role_en := a_name
      ensure
        role_en_set: role_en = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CONTACT_INFO%N")
        if attached hint as l_hint then
          Result.append ("%Nhint:")
          Result.append (l_hint.out)
          Result.append ("%N")
        end
        if attached hint_en as l_hint_en then
          Result.append ("%Nhint_en:")
          Result.append (l_hint_en.out)
          Result.append ("%N")
        end
        if attached role as l_role then
          Result.append ("%Nrole:")
          Result.append (l_role.out)
          Result.append ("%N")
        end
        if attached role_en as l_role_en then
          Result.append ("%Nrole_en:")
          Result.append (l_role_en.out)
          Result.append ("%N")
        end
      end
end

