note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CONTACT_CREATE




feature --Access

    account_holder: detachable STRING_32
      
    acquisition_cost: detachable STRING_32
      
    address_supplement: detachable STRING_32
      
    attention: detachable STRING_32
      
    bank_name: detachable STRING_32
      
    bic: detachable STRING_32
      
    buyer_reference: detachable STRING_32
      
    category: detachable STRING_32
      
    certificate_authority: detachable STRING_32
      
    certificate_number: detachable STRING_32
      
    certificate_paragraph: detachable STRING_32
      
    certificate_valid_until: detachable DATE
      
    city: detachable STRING_32
      
    company_name: detachable STRING_32
      
    contact_persons: detachable ANY
      
    contact_type: detachable CONTACT_TYPE
      
    country: detachable COUNTRY_CODE
      
    credit_limit: detachable STRING_32
      
    creditor_account_skr03: detachable STRING_32
      
    creditor_account_skr04: detachable STRING_32
      
    currency: detachable STRING_32
      
    custom_fields: detachable ANY
      
    customer_number: detachable STRING_32
      
    debitor_account_skr03: detachable STRING_32
      
    debitor_account_skr04: detachable STRING_32
      
    default_debitor_number: detachable STRING_32
      
    delivery_block: BOOLEAN
      
    department: detachable STRING_32
      
    discount_days: INTEGER_32
      
    discount_percentage: detachable STRING_32
      
    donation_receipt_eligible: BOOLEAN
      
    email: detachable STRING_32
      
    external_id: detachable STRING_32
      
    fax: detachable STRING_32
      
    iban: detachable STRING_32
      
    industry: detachable STRING_32
      
    is_active: BOOLEAN
      
    is_member: BOOLEAN
      
    is_nonprofit: BOOLEAN
      
    last_contact_date: detachable DATE
      
    last_purchase_date: detachable DATE
      
    leitweg_id: detachable STRING_32
      
    lifetime_value: detachable STRING_32
      
    mandate_date: detachable DATE
      
    mandate_reference: detachable STRING_32
      
    marketing_consent: BOOLEAN
      
    marketing_consent_at: detachable DATE_TIME
      
    marketing_consent_source: detachable STRING_32
      
    mobile: detachable STRING_32
      
    name: detachable STRING_32
      
    next_contact_date: detachable DATE
      
    notes: detachable STRING_32
      
    opening_balance: detachable STRING_32
      
    opening_balance_date: detachable DATE
      
    order_reference: detachable STRING_32
      
    payment_block: BOOLEAN
      
    payment_grace_period_days: INTEGER_32
      
    payment_methods: detachable LIST [STRING_32]
      
    payment_terms: detachable STRING_32
      
    phone: detachable STRING_32
      
    rating: INTEGER_32
      
    sales_representative: detachable STRING_32
      
    sepa_batch_booking: BOOLEAN
      
    sepa_sequence_type: detachable SEPA_SEQUENCE_TYPE
      
    social_media: detachable ANY
      
    source: detachable STRING_32
      
    state: detachable STRING_32
      
    street: detachable STRING_32
      
    street_number: detachable STRING_32
      
    supplier_number: detachable STRING_32
      
    tags: detachable LIST [STRING_32]
      
    tax_country: detachable COUNTRY_CODE
      
    tax_number: detachable STRING_32
      
    tax_office: detachable STRING_32
      
    total_invoices: INTEGER_32
      
    total_revenue: detachable STRING_32
      
    vat_id: detachable STRING_32
      
    vat_id_validated: BOOLEAN
      
    vat_id_validation_date: detachable DATE
      
    website: detachable STRING_32
      
    zip: detachable STRING_32
      

feature -- Change Element

    set_account_holder (a_name: like account_holder)
        -- Set 'account_holder' with 'a_name'.
      do
        account_holder := a_name
      ensure
        account_holder_set: account_holder = a_name
      end

    set_acquisition_cost (a_name: like acquisition_cost)
        -- Set 'acquisition_cost' with 'a_name'.
      do
        acquisition_cost := a_name
      ensure
        acquisition_cost_set: acquisition_cost = a_name
      end

    set_address_supplement (a_name: like address_supplement)
        -- Set 'address_supplement' with 'a_name'.
      do
        address_supplement := a_name
      ensure
        address_supplement_set: address_supplement = a_name
      end

    set_attention (a_name: like attention)
        -- Set 'attention' with 'a_name'.
      do
        attention := a_name
      ensure
        attention_set: attention = a_name
      end

    set_bank_name (a_name: like bank_name)
        -- Set 'bank_name' with 'a_name'.
      do
        bank_name := a_name
      ensure
        bank_name_set: bank_name = a_name
      end

    set_bic (a_name: like bic)
        -- Set 'bic' with 'a_name'.
      do
        bic := a_name
      ensure
        bic_set: bic = a_name
      end

    set_buyer_reference (a_name: like buyer_reference)
        -- Set 'buyer_reference' with 'a_name'.
      do
        buyer_reference := a_name
      ensure
        buyer_reference_set: buyer_reference = a_name
      end

    set_category (a_name: like category)
        -- Set 'category' with 'a_name'.
      do
        category := a_name
      ensure
        category_set: category = a_name
      end

    set_certificate_authority (a_name: like certificate_authority)
        -- Set 'certificate_authority' with 'a_name'.
      do
        certificate_authority := a_name
      ensure
        certificate_authority_set: certificate_authority = a_name
      end

    set_certificate_number (a_name: like certificate_number)
        -- Set 'certificate_number' with 'a_name'.
      do
        certificate_number := a_name
      ensure
        certificate_number_set: certificate_number = a_name
      end

    set_certificate_paragraph (a_name: like certificate_paragraph)
        -- Set 'certificate_paragraph' with 'a_name'.
      do
        certificate_paragraph := a_name
      ensure
        certificate_paragraph_set: certificate_paragraph = a_name
      end

    set_certificate_valid_until (a_name: like certificate_valid_until)
        -- Set 'certificate_valid_until' with 'a_name'.
      do
        certificate_valid_until := a_name
      ensure
        certificate_valid_until_set: certificate_valid_until = a_name
      end

    set_city (a_name: like city)
        -- Set 'city' with 'a_name'.
      do
        city := a_name
      ensure
        city_set: city = a_name
      end

    set_company_name (a_name: like company_name)
        -- Set 'company_name' with 'a_name'.
      do
        company_name := a_name
      ensure
        company_name_set: company_name = a_name
      end

    set_contact_persons (a_name: like contact_persons)
        -- Set 'contact_persons' with 'a_name'.
      do
        contact_persons := a_name
      ensure
        contact_persons_set: contact_persons = a_name
      end

    set_contact_type (a_name: like contact_type)
        -- Set 'contact_type' with 'a_name'.
      do
        contact_type := a_name
      ensure
        contact_type_set: contact_type = a_name
      end

    set_country (a_name: like country)
        -- Set 'country' with 'a_name'.
      do
        country := a_name
      ensure
        country_set: country = a_name
      end

    set_credit_limit (a_name: like credit_limit)
        -- Set 'credit_limit' with 'a_name'.
      do
        credit_limit := a_name
      ensure
        credit_limit_set: credit_limit = a_name
      end

    set_creditor_account_skr03 (a_name: like creditor_account_skr03)
        -- Set 'creditor_account_skr03' with 'a_name'.
      do
        creditor_account_skr03 := a_name
      ensure
        creditor_account_skr03_set: creditor_account_skr03 = a_name
      end

    set_creditor_account_skr04 (a_name: like creditor_account_skr04)
        -- Set 'creditor_account_skr04' with 'a_name'.
      do
        creditor_account_skr04 := a_name
      ensure
        creditor_account_skr04_set: creditor_account_skr04 = a_name
      end

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_custom_fields (a_name: like custom_fields)
        -- Set 'custom_fields' with 'a_name'.
      do
        custom_fields := a_name
      ensure
        custom_fields_set: custom_fields = a_name
      end

    set_customer_number (a_name: like customer_number)
        -- Set 'customer_number' with 'a_name'.
      do
        customer_number := a_name
      ensure
        customer_number_set: customer_number = a_name
      end

    set_debitor_account_skr03 (a_name: like debitor_account_skr03)
        -- Set 'debitor_account_skr03' with 'a_name'.
      do
        debitor_account_skr03 := a_name
      ensure
        debitor_account_skr03_set: debitor_account_skr03 = a_name
      end

    set_debitor_account_skr04 (a_name: like debitor_account_skr04)
        -- Set 'debitor_account_skr04' with 'a_name'.
      do
        debitor_account_skr04 := a_name
      ensure
        debitor_account_skr04_set: debitor_account_skr04 = a_name
      end

    set_default_debitor_number (a_name: like default_debitor_number)
        -- Set 'default_debitor_number' with 'a_name'.
      do
        default_debitor_number := a_name
      ensure
        default_debitor_number_set: default_debitor_number = a_name
      end

    set_delivery_block (a_name: like delivery_block)
        -- Set 'delivery_block' with 'a_name'.
      do
        delivery_block := a_name
      ensure
        delivery_block_set: delivery_block = a_name
      end

    set_department (a_name: like department)
        -- Set 'department' with 'a_name'.
      do
        department := a_name
      ensure
        department_set: department = a_name
      end

    set_discount_days (a_name: like discount_days)
        -- Set 'discount_days' with 'a_name'.
      do
        discount_days := a_name
      ensure
        discount_days_set: discount_days = a_name
      end

    set_discount_percentage (a_name: like discount_percentage)
        -- Set 'discount_percentage' with 'a_name'.
      do
        discount_percentage := a_name
      ensure
        discount_percentage_set: discount_percentage = a_name
      end

    set_donation_receipt_eligible (a_name: like donation_receipt_eligible)
        -- Set 'donation_receipt_eligible' with 'a_name'.
      do
        donation_receipt_eligible := a_name
      ensure
        donation_receipt_eligible_set: donation_receipt_eligible = a_name
      end

    set_email (a_name: like email)
        -- Set 'email' with 'a_name'.
      do
        email := a_name
      ensure
        email_set: email = a_name
      end

    set_external_id (a_name: like external_id)
        -- Set 'external_id' with 'a_name'.
      do
        external_id := a_name
      ensure
        external_id_set: external_id = a_name
      end

    set_fax (a_name: like fax)
        -- Set 'fax' with 'a_name'.
      do
        fax := a_name
      ensure
        fax_set: fax = a_name
      end

    set_iban (a_name: like iban)
        -- Set 'iban' with 'a_name'.
      do
        iban := a_name
      ensure
        iban_set: iban = a_name
      end

    set_industry (a_name: like industry)
        -- Set 'industry' with 'a_name'.
      do
        industry := a_name
      ensure
        industry_set: industry = a_name
      end

    set_is_active (a_name: like is_active)
        -- Set 'is_active' with 'a_name'.
      do
        is_active := a_name
      ensure
        is_active_set: is_active = a_name
      end

    set_is_member (a_name: like is_member)
        -- Set 'is_member' with 'a_name'.
      do
        is_member := a_name
      ensure
        is_member_set: is_member = a_name
      end

    set_is_nonprofit (a_name: like is_nonprofit)
        -- Set 'is_nonprofit' with 'a_name'.
      do
        is_nonprofit := a_name
      ensure
        is_nonprofit_set: is_nonprofit = a_name
      end

    set_last_contact_date (a_name: like last_contact_date)
        -- Set 'last_contact_date' with 'a_name'.
      do
        last_contact_date := a_name
      ensure
        last_contact_date_set: last_contact_date = a_name
      end

    set_last_purchase_date (a_name: like last_purchase_date)
        -- Set 'last_purchase_date' with 'a_name'.
      do
        last_purchase_date := a_name
      ensure
        last_purchase_date_set: last_purchase_date = a_name
      end

    set_leitweg_id (a_name: like leitweg_id)
        -- Set 'leitweg_id' with 'a_name'.
      do
        leitweg_id := a_name
      ensure
        leitweg_id_set: leitweg_id = a_name
      end

    set_lifetime_value (a_name: like lifetime_value)
        -- Set 'lifetime_value' with 'a_name'.
      do
        lifetime_value := a_name
      ensure
        lifetime_value_set: lifetime_value = a_name
      end

    set_mandate_date (a_name: like mandate_date)
        -- Set 'mandate_date' with 'a_name'.
      do
        mandate_date := a_name
      ensure
        mandate_date_set: mandate_date = a_name
      end

    set_mandate_reference (a_name: like mandate_reference)
        -- Set 'mandate_reference' with 'a_name'.
      do
        mandate_reference := a_name
      ensure
        mandate_reference_set: mandate_reference = a_name
      end

    set_marketing_consent (a_name: like marketing_consent)
        -- Set 'marketing_consent' with 'a_name'.
      do
        marketing_consent := a_name
      ensure
        marketing_consent_set: marketing_consent = a_name
      end

    set_marketing_consent_at (a_name: like marketing_consent_at)
        -- Set 'marketing_consent_at' with 'a_name'.
      do
        marketing_consent_at := a_name
      ensure
        marketing_consent_at_set: marketing_consent_at = a_name
      end

    set_marketing_consent_source (a_name: like marketing_consent_source)
        -- Set 'marketing_consent_source' with 'a_name'.
      do
        marketing_consent_source := a_name
      ensure
        marketing_consent_source_set: marketing_consent_source = a_name
      end

    set_mobile (a_name: like mobile)
        -- Set 'mobile' with 'a_name'.
      do
        mobile := a_name
      ensure
        mobile_set: mobile = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end

    set_next_contact_date (a_name: like next_contact_date)
        -- Set 'next_contact_date' with 'a_name'.
      do
        next_contact_date := a_name
      ensure
        next_contact_date_set: next_contact_date = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_opening_balance (a_name: like opening_balance)
        -- Set 'opening_balance' with 'a_name'.
      do
        opening_balance := a_name
      ensure
        opening_balance_set: opening_balance = a_name
      end

    set_opening_balance_date (a_name: like opening_balance_date)
        -- Set 'opening_balance_date' with 'a_name'.
      do
        opening_balance_date := a_name
      ensure
        opening_balance_date_set: opening_balance_date = a_name
      end

    set_order_reference (a_name: like order_reference)
        -- Set 'order_reference' with 'a_name'.
      do
        order_reference := a_name
      ensure
        order_reference_set: order_reference = a_name
      end

    set_payment_block (a_name: like payment_block)
        -- Set 'payment_block' with 'a_name'.
      do
        payment_block := a_name
      ensure
        payment_block_set: payment_block = a_name
      end

    set_payment_grace_period_days (a_name: like payment_grace_period_days)
        -- Set 'payment_grace_period_days' with 'a_name'.
      do
        payment_grace_period_days := a_name
      ensure
        payment_grace_period_days_set: payment_grace_period_days = a_name
      end

    set_payment_methods (a_name: like payment_methods)
        -- Set 'payment_methods' with 'a_name'.
      do
        payment_methods := a_name
      ensure
        payment_methods_set: payment_methods = a_name
      end

    set_payment_terms (a_name: like payment_terms)
        -- Set 'payment_terms' with 'a_name'.
      do
        payment_terms := a_name
      ensure
        payment_terms_set: payment_terms = a_name
      end

    set_phone (a_name: like phone)
        -- Set 'phone' with 'a_name'.
      do
        phone := a_name
      ensure
        phone_set: phone = a_name
      end

    set_rating (a_name: like rating)
        -- Set 'rating' with 'a_name'.
      do
        rating := a_name
      ensure
        rating_set: rating = a_name
      end

    set_sales_representative (a_name: like sales_representative)
        -- Set 'sales_representative' with 'a_name'.
      do
        sales_representative := a_name
      ensure
        sales_representative_set: sales_representative = a_name
      end

    set_sepa_batch_booking (a_name: like sepa_batch_booking)
        -- Set 'sepa_batch_booking' with 'a_name'.
      do
        sepa_batch_booking := a_name
      ensure
        sepa_batch_booking_set: sepa_batch_booking = a_name
      end

    set_sepa_sequence_type (a_name: like sepa_sequence_type)
        -- Set 'sepa_sequence_type' with 'a_name'.
      do
        sepa_sequence_type := a_name
      ensure
        sepa_sequence_type_set: sepa_sequence_type = a_name
      end

    set_social_media (a_name: like social_media)
        -- Set 'social_media' with 'a_name'.
      do
        social_media := a_name
      ensure
        social_media_set: social_media = a_name
      end

    set_source (a_name: like source)
        -- Set 'source' with 'a_name'.
      do
        source := a_name
      ensure
        source_set: source = a_name
      end

    set_state (a_name: like state)
        -- Set 'state' with 'a_name'.
      do
        state := a_name
      ensure
        state_set: state = a_name
      end

    set_street (a_name: like street)
        -- Set 'street' with 'a_name'.
      do
        street := a_name
      ensure
        street_set: street = a_name
      end

    set_street_number (a_name: like street_number)
        -- Set 'street_number' with 'a_name'.
      do
        street_number := a_name
      ensure
        street_number_set: street_number = a_name
      end

    set_supplier_number (a_name: like supplier_number)
        -- Set 'supplier_number' with 'a_name'.
      do
        supplier_number := a_name
      ensure
        supplier_number_set: supplier_number = a_name
      end

    set_tags (a_name: like tags)
        -- Set 'tags' with 'a_name'.
      do
        tags := a_name
      ensure
        tags_set: tags = a_name
      end

    set_tax_country (a_name: like tax_country)
        -- Set 'tax_country' with 'a_name'.
      do
        tax_country := a_name
      ensure
        tax_country_set: tax_country = a_name
      end

    set_tax_number (a_name: like tax_number)
        -- Set 'tax_number' with 'a_name'.
      do
        tax_number := a_name
      ensure
        tax_number_set: tax_number = a_name
      end

    set_tax_office (a_name: like tax_office)
        -- Set 'tax_office' with 'a_name'.
      do
        tax_office := a_name
      ensure
        tax_office_set: tax_office = a_name
      end

    set_total_invoices (a_name: like total_invoices)
        -- Set 'total_invoices' with 'a_name'.
      do
        total_invoices := a_name
      ensure
        total_invoices_set: total_invoices = a_name
      end

    set_total_revenue (a_name: like total_revenue)
        -- Set 'total_revenue' with 'a_name'.
      do
        total_revenue := a_name
      ensure
        total_revenue_set: total_revenue = a_name
      end

    set_vat_id (a_name: like vat_id)
        -- Set 'vat_id' with 'a_name'.
      do
        vat_id := a_name
      ensure
        vat_id_set: vat_id = a_name
      end

    set_vat_id_validated (a_name: like vat_id_validated)
        -- Set 'vat_id_validated' with 'a_name'.
      do
        vat_id_validated := a_name
      ensure
        vat_id_validated_set: vat_id_validated = a_name
      end

    set_vat_id_validation_date (a_name: like vat_id_validation_date)
        -- Set 'vat_id_validation_date' with 'a_name'.
      do
        vat_id_validation_date := a_name
      ensure
        vat_id_validation_date_set: vat_id_validation_date = a_name
      end

    set_website (a_name: like website)
        -- Set 'website' with 'a_name'.
      do
        website := a_name
      ensure
        website_set: website = a_name
      end

    set_zip (a_name: like zip)
        -- Set 'zip' with 'a_name'.
      do
        zip := a_name
      ensure
        zip_set: zip = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CONTACT_CREATE%N")
        if attached account_holder as l_account_holder then
          Result.append ("%Naccount_holder:")
          Result.append (l_account_holder.out)
          Result.append ("%N")
        end
        if attached acquisition_cost as l_acquisition_cost then
          Result.append ("%Nacquisition_cost:")
          Result.append (l_acquisition_cost.out)
          Result.append ("%N")
        end
        if attached address_supplement as l_address_supplement then
          Result.append ("%Naddress_supplement:")
          Result.append (l_address_supplement.out)
          Result.append ("%N")
        end
        if attached attention as l_attention then
          Result.append ("%Nattention:")
          Result.append (l_attention.out)
          Result.append ("%N")
        end
        if attached bank_name as l_bank_name then
          Result.append ("%Nbank_name:")
          Result.append (l_bank_name.out)
          Result.append ("%N")
        end
        if attached bic as l_bic then
          Result.append ("%Nbic:")
          Result.append (l_bic.out)
          Result.append ("%N")
        end
        if attached buyer_reference as l_buyer_reference then
          Result.append ("%Nbuyer_reference:")
          Result.append (l_buyer_reference.out)
          Result.append ("%N")
        end
        if attached category as l_category then
          Result.append ("%Ncategory:")
          Result.append (l_category.out)
          Result.append ("%N")
        end
        if attached certificate_authority as l_certificate_authority then
          Result.append ("%Ncertificate_authority:")
          Result.append (l_certificate_authority.out)
          Result.append ("%N")
        end
        if attached certificate_number as l_certificate_number then
          Result.append ("%Ncertificate_number:")
          Result.append (l_certificate_number.out)
          Result.append ("%N")
        end
        if attached certificate_paragraph as l_certificate_paragraph then
          Result.append ("%Ncertificate_paragraph:")
          Result.append (l_certificate_paragraph.out)
          Result.append ("%N")
        end
        if attached certificate_valid_until as l_certificate_valid_until then
          Result.append ("%Ncertificate_valid_until:")
          Result.append (l_certificate_valid_until.out)
          Result.append ("%N")
        end
        if attached city as l_city then
          Result.append ("%Ncity:")
          Result.append (l_city.out)
          Result.append ("%N")
        end
        if attached company_name as l_company_name then
          Result.append ("%Ncompany_name:")
          Result.append (l_company_name.out)
          Result.append ("%N")
        end
        if attached contact_persons as l_contact_persons then
          Result.append ("%Ncontact_persons:")
          Result.append (l_contact_persons.out)
          Result.append ("%N")
        end
        if attached contact_type as l_contact_type then
          Result.append ("%Ncontact_type:")
          Result.append (l_contact_type.out)
          Result.append ("%N")
        end
        if attached country as l_country then
          Result.append ("%Ncountry:")
          Result.append (l_country.out)
          Result.append ("%N")
        end
        if attached credit_limit as l_credit_limit then
          Result.append ("%Ncredit_limit:")
          Result.append (l_credit_limit.out)
          Result.append ("%N")
        end
        if attached creditor_account_skr03 as l_creditor_account_skr03 then
          Result.append ("%Ncreditor_account_skr03:")
          Result.append (l_creditor_account_skr03.out)
          Result.append ("%N")
        end
        if attached creditor_account_skr04 as l_creditor_account_skr04 then
          Result.append ("%Ncreditor_account_skr04:")
          Result.append (l_creditor_account_skr04.out)
          Result.append ("%N")
        end
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached custom_fields as l_custom_fields then
          Result.append ("%Ncustom_fields:")
          Result.append (l_custom_fields.out)
          Result.append ("%N")
        end
        if attached customer_number as l_customer_number then
          Result.append ("%Ncustomer_number:")
          Result.append (l_customer_number.out)
          Result.append ("%N")
        end
        if attached debitor_account_skr03 as l_debitor_account_skr03 then
          Result.append ("%Ndebitor_account_skr03:")
          Result.append (l_debitor_account_skr03.out)
          Result.append ("%N")
        end
        if attached debitor_account_skr04 as l_debitor_account_skr04 then
          Result.append ("%Ndebitor_account_skr04:")
          Result.append (l_debitor_account_skr04.out)
          Result.append ("%N")
        end
        if attached default_debitor_number as l_default_debitor_number then
          Result.append ("%Ndefault_debitor_number:")
          Result.append (l_default_debitor_number.out)
          Result.append ("%N")
        end
        if attached delivery_block as l_delivery_block then
          Result.append ("%Ndelivery_block:")
          Result.append (l_delivery_block.out)
          Result.append ("%N")
        end
        if attached department as l_department then
          Result.append ("%Ndepartment:")
          Result.append (l_department.out)
          Result.append ("%N")
        end
        if attached discount_days as l_discount_days then
          Result.append ("%Ndiscount_days:")
          Result.append (l_discount_days.out)
          Result.append ("%N")
        end
        if attached discount_percentage as l_discount_percentage then
          Result.append ("%Ndiscount_percentage:")
          Result.append (l_discount_percentage.out)
          Result.append ("%N")
        end
        if attached donation_receipt_eligible as l_donation_receipt_eligible then
          Result.append ("%Ndonation_receipt_eligible:")
          Result.append (l_donation_receipt_eligible.out)
          Result.append ("%N")
        end
        if attached email as l_email then
          Result.append ("%Nemail:")
          Result.append (l_email.out)
          Result.append ("%N")
        end
        if attached external_id as l_external_id then
          Result.append ("%Nexternal_id:")
          Result.append (l_external_id.out)
          Result.append ("%N")
        end
        if attached fax as l_fax then
          Result.append ("%Nfax:")
          Result.append (l_fax.out)
          Result.append ("%N")
        end
        if attached iban as l_iban then
          Result.append ("%Niban:")
          Result.append (l_iban.out)
          Result.append ("%N")
        end
        if attached industry as l_industry then
          Result.append ("%Nindustry:")
          Result.append (l_industry.out)
          Result.append ("%N")
        end
        if attached is_active as l_is_active then
          Result.append ("%Nis_active:")
          Result.append (l_is_active.out)
          Result.append ("%N")
        end
        if attached is_member as l_is_member then
          Result.append ("%Nis_member:")
          Result.append (l_is_member.out)
          Result.append ("%N")
        end
        if attached is_nonprofit as l_is_nonprofit then
          Result.append ("%Nis_nonprofit:")
          Result.append (l_is_nonprofit.out)
          Result.append ("%N")
        end
        if attached last_contact_date as l_last_contact_date then
          Result.append ("%Nlast_contact_date:")
          Result.append (l_last_contact_date.out)
          Result.append ("%N")
        end
        if attached last_purchase_date as l_last_purchase_date then
          Result.append ("%Nlast_purchase_date:")
          Result.append (l_last_purchase_date.out)
          Result.append ("%N")
        end
        if attached leitweg_id as l_leitweg_id then
          Result.append ("%Nleitweg_id:")
          Result.append (l_leitweg_id.out)
          Result.append ("%N")
        end
        if attached lifetime_value as l_lifetime_value then
          Result.append ("%Nlifetime_value:")
          Result.append (l_lifetime_value.out)
          Result.append ("%N")
        end
        if attached mandate_date as l_mandate_date then
          Result.append ("%Nmandate_date:")
          Result.append (l_mandate_date.out)
          Result.append ("%N")
        end
        if attached mandate_reference as l_mandate_reference then
          Result.append ("%Nmandate_reference:")
          Result.append (l_mandate_reference.out)
          Result.append ("%N")
        end
        if attached marketing_consent as l_marketing_consent then
          Result.append ("%Nmarketing_consent:")
          Result.append (l_marketing_consent.out)
          Result.append ("%N")
        end
        if attached marketing_consent_at as l_marketing_consent_at then
          Result.append ("%Nmarketing_consent_at:")
          Result.append (l_marketing_consent_at.out)
          Result.append ("%N")
        end
        if attached marketing_consent_source as l_marketing_consent_source then
          Result.append ("%Nmarketing_consent_source:")
          Result.append (l_marketing_consent_source.out)
          Result.append ("%N")
        end
        if attached mobile as l_mobile then
          Result.append ("%Nmobile:")
          Result.append (l_mobile.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
        if attached next_contact_date as l_next_contact_date then
          Result.append ("%Nnext_contact_date:")
          Result.append (l_next_contact_date.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached opening_balance as l_opening_balance then
          Result.append ("%Nopening_balance:")
          Result.append (l_opening_balance.out)
          Result.append ("%N")
        end
        if attached opening_balance_date as l_opening_balance_date then
          Result.append ("%Nopening_balance_date:")
          Result.append (l_opening_balance_date.out)
          Result.append ("%N")
        end
        if attached order_reference as l_order_reference then
          Result.append ("%Norder_reference:")
          Result.append (l_order_reference.out)
          Result.append ("%N")
        end
        if attached payment_block as l_payment_block then
          Result.append ("%Npayment_block:")
          Result.append (l_payment_block.out)
          Result.append ("%N")
        end
        if attached payment_grace_period_days as l_payment_grace_period_days then
          Result.append ("%Npayment_grace_period_days:")
          Result.append (l_payment_grace_period_days.out)
          Result.append ("%N")
        end
        if attached payment_methods as l_payment_methods then
          across l_payment_methods as ic loop
            Result.append ("%N payment_methods:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached payment_terms as l_payment_terms then
          Result.append ("%Npayment_terms:")
          Result.append (l_payment_terms.out)
          Result.append ("%N")
        end
        if attached phone as l_phone then
          Result.append ("%Nphone:")
          Result.append (l_phone.out)
          Result.append ("%N")
        end
        if attached rating as l_rating then
          Result.append ("%Nrating:")
          Result.append (l_rating.out)
          Result.append ("%N")
        end
        if attached sales_representative as l_sales_representative then
          Result.append ("%Nsales_representative:")
          Result.append (l_sales_representative.out)
          Result.append ("%N")
        end
        if attached sepa_batch_booking as l_sepa_batch_booking then
          Result.append ("%Nsepa_batch_booking:")
          Result.append (l_sepa_batch_booking.out)
          Result.append ("%N")
        end
        if attached sepa_sequence_type as l_sepa_sequence_type then
          Result.append ("%Nsepa_sequence_type:")
          Result.append (l_sepa_sequence_type.out)
          Result.append ("%N")
        end
        if attached social_media as l_social_media then
          Result.append ("%Nsocial_media:")
          Result.append (l_social_media.out)
          Result.append ("%N")
        end
        if attached source as l_source then
          Result.append ("%Nsource:")
          Result.append (l_source.out)
          Result.append ("%N")
        end
        if attached state as l_state then
          Result.append ("%Nstate:")
          Result.append (l_state.out)
          Result.append ("%N")
        end
        if attached street as l_street then
          Result.append ("%Nstreet:")
          Result.append (l_street.out)
          Result.append ("%N")
        end
        if attached street_number as l_street_number then
          Result.append ("%Nstreet_number:")
          Result.append (l_street_number.out)
          Result.append ("%N")
        end
        if attached supplier_number as l_supplier_number then
          Result.append ("%Nsupplier_number:")
          Result.append (l_supplier_number.out)
          Result.append ("%N")
        end
        if attached tags as l_tags then
          across l_tags as ic loop
            Result.append ("%N tags:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached tax_country as l_tax_country then
          Result.append ("%Ntax_country:")
          Result.append (l_tax_country.out)
          Result.append ("%N")
        end
        if attached tax_number as l_tax_number then
          Result.append ("%Ntax_number:")
          Result.append (l_tax_number.out)
          Result.append ("%N")
        end
        if attached tax_office as l_tax_office then
          Result.append ("%Ntax_office:")
          Result.append (l_tax_office.out)
          Result.append ("%N")
        end
        if attached total_invoices as l_total_invoices then
          Result.append ("%Ntotal_invoices:")
          Result.append (l_total_invoices.out)
          Result.append ("%N")
        end
        if attached total_revenue as l_total_revenue then
          Result.append ("%Ntotal_revenue:")
          Result.append (l_total_revenue.out)
          Result.append ("%N")
        end
        if attached vat_id as l_vat_id then
          Result.append ("%Nvat_id:")
          Result.append (l_vat_id.out)
          Result.append ("%N")
        end
        if attached vat_id_validated as l_vat_id_validated then
          Result.append ("%Nvat_id_validated:")
          Result.append (l_vat_id_validated.out)
          Result.append ("%N")
        end
        if attached vat_id_validation_date as l_vat_id_validation_date then
          Result.append ("%Nvat_id_validation_date:")
          Result.append (l_vat_id_validation_date.out)
          Result.append ("%N")
        end
        if attached website as l_website then
          Result.append ("%Nwebsite:")
          Result.append (l_website.out)
          Result.append ("%N")
        end
        if attached zip as l_zip then
          Result.append ("%Nzip:")
          Result.append (l_zip.out)
          Result.append ("%N")
        end
      end
end

