note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CONTACT_TIMELINE_RESPONSE




feature --Access

    contact_id: detachable STRING_32
      
    events: detachable LIST [TIMELINE_EVENT]
      

feature -- Change Element

    set_contact_id (a_name: like contact_id)
        -- Set 'contact_id' with 'a_name'.
      do
        contact_id := a_name
      ensure
        contact_id_set: contact_id = a_name
      end

    set_events (a_name: like events)
        -- Set 'events' with 'a_name'.
      do
        events := a_name
      ensure
        events_set: events = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CONTACT_TIMELINE_RESPONSE%N")
        if attached contact_id as l_contact_id then
          Result.append ("%Ncontact_id:")
          Result.append (l_contact_id.out)
          Result.append ("%N")
        end
        if attached events as l_events then
          across l_events as ic loop
            Result.append ("%N events:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
      end
end

