note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CREATE_SHIPMENT_REQUEST




feature --Access

    carrier: detachable STRING_32
      -- Carrier name as configured in shipping settings: `ups` or `dhl`.
    service: detachable STRING_32
      
    weight_kg: REAL_64
      

feature -- Change Element

    set_carrier (a_name: like carrier)
        -- Set 'carrier' with 'a_name'.
      do
        carrier := a_name
      ensure
        carrier_set: carrier = a_name
      end

    set_service (a_name: like service)
        -- Set 'service' with 'a_name'.
      do
        service := a_name
      ensure
        service_set: service = a_name
      end

    set_weight_kg (a_name: like weight_kg)
        -- Set 'weight_kg' with 'a_name'.
      do
        weight_kg := a_name
      ensure
        weight_kg_set: weight_kg = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CREATE_SHIPMENT_REQUEST%N")
        if attached carrier as l_carrier then
          Result.append ("%Ncarrier:")
          Result.append (l_carrier.out)
          Result.append ("%N")
        end
        if attached service as l_service then
          Result.append ("%Nservice:")
          Result.append (l_service.out)
          Result.append ("%N")
        end
        if attached weight_kg as l_weight_kg then
          Result.append ("%Nweight_kg:")
          Result.append (l_weight_kg.out)
          Result.append ("%N")
        end
      end
end

