note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CREATE_CHANNEL_DTO




feature --Access

    channel_type: detachable STRING_32
      
    config: detachable ANY
      
    name: detachable STRING_32
      

feature -- Change Element

    set_channel_type (a_name: like channel_type)
        -- Set 'channel_type' with 'a_name'.
      do
        channel_type := a_name
      ensure
        channel_type_set: channel_type = a_name
      end

    set_config (a_name: like config)
        -- Set 'config' with 'a_name'.
      do
        config := a_name
      ensure
        config_set: config = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CREATE_CHANNEL_DTO%N")
        if attached channel_type as l_channel_type then
          Result.append ("%Nchannel_type:")
          Result.append (l_channel_type.out)
          Result.append ("%N")
        end
        if attached config as l_config then
          Result.append ("%Nconfig:")
          Result.append (l_config.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
      end
end

