note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class CUSTOMER_GROUP




feature --Access

    description: detachable STRING_32
      
    member_ids: detachable LIST [STRING_32]
      -- Contact ids that are members of this group.
    membership_filter: detachable STRING_32
      -- Rule description for membership, e.g. \"orders > 5 last 12 months\".
    name: detachable STRING_32
      -- Unique group name, e.g. \"VIP\", \"Wholesale\", \"Newsletter\".

feature -- Change Element

    set_description (a_name: like description)
        -- Set 'description' with 'a_name'.
      do
        description := a_name
      ensure
        description_set: description = a_name
      end

    set_member_ids (a_name: like member_ids)
        -- Set 'member_ids' with 'a_name'.
      do
        member_ids := a_name
      ensure
        member_ids_set: member_ids = a_name
      end

    set_membership_filter (a_name: like membership_filter)
        -- Set 'membership_filter' with 'a_name'.
      do
        membership_filter := a_name
      ensure
        membership_filter_set: membership_filter = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass CUSTOMER_GROUP%N")
        if attached description as l_description then
          Result.append ("%Ndescription:")
          Result.append (l_description.out)
          Result.append ("%N")
        end
        if attached member_ids as l_member_ids then
          across l_member_ids as ic loop
            Result.append ("%N member_ids:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached membership_filter as l_membership_filter then
          Result.append ("%Nmembership_filter:")
          Result.append (l_membership_filter.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
      end
end

