note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class DHL_CREDENTIALS




feature --Access

    api_key: detachable STRING_32
      -- DHL-API-Key from developer.dhl.com (required for tracking).
    client_id: detachable STRING_32
      -- Client credentials from the DHL developer app; required for label creation.
    client_secret: detachable STRING_32
      

feature -- Change Element

    set_api_key (a_name: like api_key)
        -- Set 'api_key' with 'a_name'.
      do
        api_key := a_name
      ensure
        api_key_set: api_key = a_name
      end

    set_client_id (a_name: like client_id)
        -- Set 'client_id' with 'a_name'.
      do
        client_id := a_name
      ensure
        client_id_set: client_id = a_name
      end

    set_client_secret (a_name: like client_secret)
        -- Set 'client_secret' with 'a_name'.
      do
        client_secret := a_name
      ensure
        client_secret_set: client_secret = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass DHL_CREDENTIALS%N")
        if attached api_key as l_api_key then
          Result.append ("%Napi_key:")
          Result.append (l_api_key.out)
          Result.append ("%N")
        end
        if attached client_id as l_client_id then
          Result.append ("%Nclient_id:")
          Result.append (l_client_id.out)
          Result.append ("%N")
        end
        if attached client_secret as l_client_secret then
          Result.append ("%Nclient_secret:")
          Result.append (l_client_secret.out)
          Result.append ("%N")
        end
      end
end

