note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class DOCUMENT_TYPE

feature -- Access

  value: detachable STRING_32
      -- enumerated value.
    note
            option: stable
    attribute
    end

feature -- Enum

 val_invoice: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("invoice")
    end

 val_creditnote: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("creditnote")
    end

 val_advancepayment: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("advancepayment")
    end

 val_downpaymentinvoice: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("downpaymentinvoice")
    end

 val_deliverynote: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("deliverynote")
    end

 val_orderconfirmation: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("orderconfirmation")
    end

 val_quotation: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("quotation")
    end

 val_proformainvoice: DOCUMENT_TYPE
    once
      create Result
      Result.set_value ("proformainvoice")
    end


feature -- Element Change

  set_value (a_val: like value)
      -- Set `value' with `a_value'.
    do
      value := a_val
    ensure
      value_set: value = a_val
    end


end

