note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class EMISSION_ENTRY




feature --Access

    activity_value: detachable STRING_32
      -- Activity amount in `unit` (kWh, l, km, t, tkm, EUR).
    category_id: detachable STRING_32
      -- GHG-Protocol category key, e.g. \"purchased_goods\", \"business_travel\".
    description: detachable STRING_32
      
    ef_source: detachable STRING_32
      -- Emission-factor source, e.g. \"UBA-2024\", \"DEFRA-2024\".
    ef_version: detachable STRING_32
      
    method: detachable EMISSION_METHOD
      -- \"activity\" | \"spend\" | \"supplier\".
    scope: detachable GHG_SCOPE
      -- GHG scope: \"1\" | \"2\" | \"3\".
    tco2e: detachable STRING_32
      -- Computed server-side: activity * factor / 1000, rounded to 4 dp.
    unit: detachable STRING_32
      -- Unit of the activity value.
    updated_at: detachable DATE_TIME
      
    year: INTEGER_32
      -- Reporting year.

feature -- Change Element

    set_activity_value (a_name: like activity_value)
        -- Set 'activity_value' with 'a_name'.
      do
        activity_value := a_name
      ensure
        activity_value_set: activity_value = a_name
      end

    set_category_id (a_name: like category_id)
        -- Set 'category_id' with 'a_name'.
      do
        category_id := a_name
      ensure
        category_id_set: category_id = a_name
      end

    set_description (a_name: like description)
        -- Set 'description' with 'a_name'.
      do
        description := a_name
      ensure
        description_set: description = a_name
      end

    set_ef_source (a_name: like ef_source)
        -- Set 'ef_source' with 'a_name'.
      do
        ef_source := a_name
      ensure
        ef_source_set: ef_source = a_name
      end

    set_ef_version (a_name: like ef_version)
        -- Set 'ef_version' with 'a_name'.
      do
        ef_version := a_name
      ensure
        ef_version_set: ef_version = a_name
      end

    set_method (a_name: like method)
        -- Set 'method' with 'a_name'.
      do
        method := a_name
      ensure
        method_set: method = a_name
      end

    set_scope (a_name: like scope)
        -- Set 'scope' with 'a_name'.
      do
        scope := a_name
      ensure
        scope_set: scope = a_name
      end

    set_tco2e (a_name: like tco2e)
        -- Set 'tco2e' with 'a_name'.
      do
        tco2e := a_name
      ensure
        tco2e_set: tco2e = a_name
      end

    set_unit (a_name: like unit)
        -- Set 'unit' with 'a_name'.
      do
        unit := a_name
      ensure
        unit_set: unit = a_name
      end

    set_updated_at (a_name: like updated_at)
        -- Set 'updated_at' with 'a_name'.
      do
        updated_at := a_name
      ensure
        updated_at_set: updated_at = a_name
      end

    set_year (a_name: like year)
        -- Set 'year' with 'a_name'.
      do
        year := a_name
      ensure
        year_set: year = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass EMISSION_ENTRY%N")
        if attached activity_value as l_activity_value then
          Result.append ("%Nactivity_value:")
          Result.append (l_activity_value.out)
          Result.append ("%N")
        end
        if attached category_id as l_category_id then
          Result.append ("%Ncategory_id:")
          Result.append (l_category_id.out)
          Result.append ("%N")
        end
        if attached description as l_description then
          Result.append ("%Ndescription:")
          Result.append (l_description.out)
          Result.append ("%N")
        end
        if attached ef_source as l_ef_source then
          Result.append ("%Nef_source:")
          Result.append (l_ef_source.out)
          Result.append ("%N")
        end
        if attached ef_version as l_ef_version then
          Result.append ("%Nef_version:")
          Result.append (l_ef_version.out)
          Result.append ("%N")
        end
        if attached method as l_method then
          Result.append ("%Nmethod:")
          Result.append (l_method.out)
          Result.append ("%N")
        end
        if attached scope as l_scope then
          Result.append ("%Nscope:")
          Result.append (l_scope.out)
          Result.append ("%N")
        end
        if attached tco2e as l_tco2e then
          Result.append ("%Ntco2e:")
          Result.append (l_tco2e.out)
          Result.append ("%N")
        end
        if attached unit as l_unit then
          Result.append ("%Nunit:")
          Result.append (l_unit.out)
          Result.append ("%N")
        end
        if attached updated_at as l_updated_at then
          Result.append ("%Nupdated_at:")
          Result.append (l_updated_at.out)
          Result.append ("%N")
        end
        if attached year as l_year then
          Result.append ("%Nyear:")
          Result.append (l_year.out)
          Result.append ("%N")
        end
      end
end

