note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class EUER_ZEILE_DETAIL




feature --Access

    abschnitt: detachable STRING_32
      
    betrag_gesamt: detachable STRING_32
      
    bezeichnung: detachable STRING_32
      
    kategorien: detachable LIST [EUER_KAT_SUMME]
      
    zeile: INTEGER_32
      

feature -- Change Element

    set_abschnitt (a_name: like abschnitt)
        -- Set 'abschnitt' with 'a_name'.
      do
        abschnitt := a_name
      ensure
        abschnitt_set: abschnitt = a_name
      end

    set_betrag_gesamt (a_name: like betrag_gesamt)
        -- Set 'betrag_gesamt' with 'a_name'.
      do
        betrag_gesamt := a_name
      ensure
        betrag_gesamt_set: betrag_gesamt = a_name
      end

    set_bezeichnung (a_name: like bezeichnung)
        -- Set 'bezeichnung' with 'a_name'.
      do
        bezeichnung := a_name
      ensure
        bezeichnung_set: bezeichnung = a_name
      end

    set_kategorien (a_name: like kategorien)
        -- Set 'kategorien' with 'a_name'.
      do
        kategorien := a_name
      ensure
        kategorien_set: kategorien = a_name
      end

    set_zeile (a_name: like zeile)
        -- Set 'zeile' with 'a_name'.
      do
        zeile := a_name
      ensure
        zeile_set: zeile = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass EUER_ZEILE_DETAIL%N")
        if attached abschnitt as l_abschnitt then
          Result.append ("%Nabschnitt:")
          Result.append (l_abschnitt.out)
          Result.append ("%N")
        end
        if attached betrag_gesamt as l_betrag_gesamt then
          Result.append ("%Nbetrag_gesamt:")
          Result.append (l_betrag_gesamt.out)
          Result.append ("%N")
        end
        if attached bezeichnung as l_bezeichnung then
          Result.append ("%Nbezeichnung:")
          Result.append (l_bezeichnung.out)
          Result.append ("%N")
        end
        if attached kategorien as l_kategorien then
          across l_kategorien as ic loop
            Result.append ("%N kategorien:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached zeile as l_zeile then
          Result.append ("%Nzeile:")
          Result.append (l_zeile.out)
          Result.append ("%N")
        end
      end
end

