note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class GDPR_API_KEY




feature --Access

    created_at: detachable DATE_TIME
      
    expires_at: detachable DATE_TIME
      
    id: detachable UUID
      
    key_id: detachable UUID
      
    name: detachable STRING_32
      
    revoked: BOOLEAN
      

feature -- Change Element

    set_created_at (a_name: like created_at)
        -- Set 'created_at' with 'a_name'.
      do
        created_at := a_name
      ensure
        created_at_set: created_at = a_name
      end

    set_expires_at (a_name: like expires_at)
        -- Set 'expires_at' with 'a_name'.
      do
        expires_at := a_name
      ensure
        expires_at_set: expires_at = a_name
      end

    set_id (a_name: like id)
        -- Set 'id' with 'a_name'.
      do
        id := a_name
      ensure
        id_set: id = a_name
      end

    set_key_id (a_name: like key_id)
        -- Set 'key_id' with 'a_name'.
      do
        key_id := a_name
      ensure
        key_id_set: key_id = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end

    set_revoked (a_name: like revoked)
        -- Set 'revoked' with 'a_name'.
      do
        revoked := a_name
      ensure
        revoked_set: revoked = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass GDPR_API_KEY%N")
        if attached created_at as l_created_at then
          Result.append ("%Ncreated_at:")
          Result.append (l_created_at.out)
          Result.append ("%N")
        end
        if attached expires_at as l_expires_at then
          Result.append ("%Nexpires_at:")
          Result.append (l_expires_at.out)
          Result.append ("%N")
        end
        if attached id as l_id then
          Result.append ("%Nid:")
          Result.append (l_id.out)
          Result.append ("%N")
        end
        if attached key_id as l_key_id then
          Result.append ("%Nkey_id:")
          Result.append (l_key_id.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
        if attached revoked as l_revoked then
          Result.append ("%Nrevoked:")
          Result.append (l_revoked.out)
          Result.append ("%N")
        end
      end
end

