note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class GENERATE_COUNT_REQUEST




feature --Access

    notes: detachable STRING_32
      
    product_ids: detachable LIST [UUID]
      
    warehouse_id: detachable STRING_32
      

feature -- Change Element

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_product_ids (a_name: like product_ids)
        -- Set 'product_ids' with 'a_name'.
      do
        product_ids := a_name
      ensure
        product_ids_set: product_ids = a_name
      end

    set_warehouse_id (a_name: like warehouse_id)
        -- Set 'warehouse_id' with 'a_name'.
      do
        warehouse_id := a_name
      ensure
        warehouse_id_set: warehouse_id = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass GENERATE_COUNT_REQUEST%N")
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached product_ids as l_product_ids then
          across l_product_ids as ic loop
            Result.append ("%N product_ids:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached warehouse_id as l_warehouse_id then
          Result.append ("%Nwarehouse_id:")
          Result.append (l_warehouse_id.out)
          Result.append ("%N")
        end
      end
end

