note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class GU_V_REPORT




feature --Access

    expenses: detachable LIST [GU_V_ITEM]
      
    generated_at: detachable STRING_32
      
    net_income: detachable STRING_32
      
    period: detachable STRING_32
      
    revenue: detachable LIST [GU_V_ITEM]
      
    total_expenses: detachable STRING_32
      
    total_revenue: detachable STRING_32
      

feature -- Change Element

    set_expenses (a_name: like expenses)
        -- Set 'expenses' with 'a_name'.
      do
        expenses := a_name
      ensure
        expenses_set: expenses = a_name
      end

    set_generated_at (a_name: like generated_at)
        -- Set 'generated_at' with 'a_name'.
      do
        generated_at := a_name
      ensure
        generated_at_set: generated_at = a_name
      end

    set_net_income (a_name: like net_income)
        -- Set 'net_income' with 'a_name'.
      do
        net_income := a_name
      ensure
        net_income_set: net_income = a_name
      end

    set_period (a_name: like period)
        -- Set 'period' with 'a_name'.
      do
        period := a_name
      ensure
        period_set: period = a_name
      end

    set_revenue (a_name: like revenue)
        -- Set 'revenue' with 'a_name'.
      do
        revenue := a_name
      ensure
        revenue_set: revenue = a_name
      end

    set_total_expenses (a_name: like total_expenses)
        -- Set 'total_expenses' with 'a_name'.
      do
        total_expenses := a_name
      ensure
        total_expenses_set: total_expenses = a_name
      end

    set_total_revenue (a_name: like total_revenue)
        -- Set 'total_revenue' with 'a_name'.
      do
        total_revenue := a_name
      ensure
        total_revenue_set: total_revenue = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass GU_V_REPORT%N")
        if attached expenses as l_expenses then
          across l_expenses as ic loop
            Result.append ("%N expenses:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached generated_at as l_generated_at then
          Result.append ("%Ngenerated_at:")
          Result.append (l_generated_at.out)
          Result.append ("%N")
        end
        if attached net_income as l_net_income then
          Result.append ("%Nnet_income:")
          Result.append (l_net_income.out)
          Result.append ("%N")
        end
        if attached period as l_period then
          Result.append ("%Nperiod:")
          Result.append (l_period.out)
          Result.append ("%N")
        end
        if attached revenue as l_revenue then
          across l_revenue as ic loop
            Result.append ("%N revenue:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_expenses as l_total_expenses then
          Result.append ("%Ntotal_expenses:")
          Result.append (l_total_expenses.out)
          Result.append ("%N")
        end
        if attached total_revenue as l_total_revenue then
          Result.append ("%Ntotal_revenue:")
          Result.append (l_total_revenue.out)
          Result.append ("%N")
        end
      end
end

