note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class INSTITUTE_DEADLINES




feature --Access

    abschlusspruefung_months: INTEGER_32
      -- HGB § 340k/§ 341k: Abschlussprüfung (5 Monate).
    jahresabschluss_bafin_months: INTEGER_32
      -- KWG § 26: Jahresabschluss an die BaFin (3 Monate, nur KWG-Institute).
    offenlegung_months: INTEGER_32
      -- HGB § 325 Abs. 4: Offenlegung (4 kapitalmarktorientiert / 12 sonst).

feature -- Change Element

    set_abschlusspruefung_months (a_name: like abschlusspruefung_months)
        -- Set 'abschlusspruefung_months' with 'a_name'.
      do
        abschlusspruefung_months := a_name
      ensure
        abschlusspruefung_months_set: abschlusspruefung_months = a_name
      end

    set_jahresabschluss_bafin_months (a_name: like jahresabschluss_bafin_months)
        -- Set 'jahresabschluss_bafin_months' with 'a_name'.
      do
        jahresabschluss_bafin_months := a_name
      ensure
        jahresabschluss_bafin_months_set: jahresabschluss_bafin_months = a_name
      end

    set_offenlegung_months (a_name: like offenlegung_months)
        -- Set 'offenlegung_months' with 'a_name'.
      do
        offenlegung_months := a_name
      ensure
        offenlegung_months_set: offenlegung_months = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass INSTITUTE_DEADLINES%N")
        if attached abschlusspruefung_months as l_abschlusspruefung_months then
          Result.append ("%Nabschlusspruefung_months:")
          Result.append (l_abschlusspruefung_months.out)
          Result.append ("%N")
        end
        if attached jahresabschluss_bafin_months as l_jahresabschluss_bafin_months then
          Result.append ("%Njahresabschluss_bafin_months:")
          Result.append (l_jahresabschluss_bafin_months.out)
          Result.append ("%N")
        end
        if attached offenlegung_months as l_offenlegung_months then
          Result.append ("%Noffenlegung_months:")
          Result.append (l_offenlegung_months.out)
          Result.append ("%N")
        end
      end
end

