note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class INVOICE




feature --Access

    attachments: detachable ANY
      
    billing_period_end: detachable DATE
      
    billing_period_start: detachable DATE
      
    cancellation_date: detachable DATE
      
    cancellation_invoice_id: detachable STRING_32
      -- References the invoice entity.
    cancellation_reason: detachable STRING_32
      
    contract_id: detachable UUID
      -- References the contract entity.
    currency: detachable CURRENCY_CODE
      
    customer_id: detachable STRING_32
      -- References the customer entity.
    discount_amount: detachable STRING_32
      
    discount_days: INTEGER_32
      
    discount_percentage: detachable STRING_32
      
    document_type: detachable DOCUMENT_TYPE
      
    dunning_level: INTEGER_32
      
    input_vat_amount: detachable STRING_32
      
    input_vat_deductible: BOOLEAN
      
    input_vat_percentage: detachable STRING_32
      
    introduction_text: detachable STRING_32
      
    invoice_type: detachable INVOICE_TYPE
      
    is_cancelled: BOOLEAN
      
    is_draft: BOOLEAN
      
    is_eu_acquisition: BOOLEAN
      
    is_eu_delivery: BOOLEAN
      
    is_intra_community_acquisition: BOOLEAN
      
    is_reverse_charge: BOOLEAN
      
    issue_date: detachable DATE
      
    ledger_account: detachable STRING_32
      
    line_items: detachable ANY
      
    margin25a: BOOLEAN
      
    margin25a_gross: detachable STRING_32
      
    margin25a_purchase_price: detachable STRING_32
      
    notes: detachable STRING_32
      
    order_number: detachable STRING_32
      
    original_pdf_path: detachable STRING_32
      
    paid_amount: detachable STRING_32
      
    payment_due_date: detachable DATE
      
    payment_status: detachable PAYMENT_STATUS
      
    payment_terms_text: detachable STRING_32
      
    preceding_sales_voucher_id: detachable STRING_32
      -- References the preceding sales voucher entity.
    preceding_sales_voucher_type: detachable PRECEDING_SALES_VOUCHER_TYPE
      
    receipt_confirmation_available: BOOLEAN
      
    related_invoice_id: detachable UUID
      -- References the invoice entity.
    relationship_type: detachable STRING_32
      
    sender_snapshot: detachable ANY
      
    sent_at: detachable DATE_TIME
      
    service_period_end: detachable DATE
      
    service_period_start: detachable DATE
      
    status: detachable INVOICE_STATUS
      
    subtotal: detachable STRING_32
      
    supplier_id: detachable STRING_32
      -- References the supplier entity.
    tax_exemption_reason: detachable STRING_32
      
    total_amount: detachable STRING_32
      
    total_tax: detachable STRING_32
      
    vat_country: detachable COUNTRY_CODE
      
    vat_special_case: detachable STRING_32
      

feature -- Change Element

    set_attachments (a_name: like attachments)
        -- Set 'attachments' with 'a_name'.
      do
        attachments := a_name
      ensure
        attachments_set: attachments = a_name
      end

    set_billing_period_end (a_name: like billing_period_end)
        -- Set 'billing_period_end' with 'a_name'.
      do
        billing_period_end := a_name
      ensure
        billing_period_end_set: billing_period_end = a_name
      end

    set_billing_period_start (a_name: like billing_period_start)
        -- Set 'billing_period_start' with 'a_name'.
      do
        billing_period_start := a_name
      ensure
        billing_period_start_set: billing_period_start = a_name
      end

    set_cancellation_date (a_name: like cancellation_date)
        -- Set 'cancellation_date' with 'a_name'.
      do
        cancellation_date := a_name
      ensure
        cancellation_date_set: cancellation_date = a_name
      end

    set_cancellation_invoice_id (a_name: like cancellation_invoice_id)
        -- Set 'cancellation_invoice_id' with 'a_name'.
      do
        cancellation_invoice_id := a_name
      ensure
        cancellation_invoice_id_set: cancellation_invoice_id = a_name
      end

    set_cancellation_reason (a_name: like cancellation_reason)
        -- Set 'cancellation_reason' with 'a_name'.
      do
        cancellation_reason := a_name
      ensure
        cancellation_reason_set: cancellation_reason = a_name
      end

    set_contract_id (a_name: like contract_id)
        -- Set 'contract_id' with 'a_name'.
      do
        contract_id := a_name
      ensure
        contract_id_set: contract_id = a_name
      end

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_customer_id (a_name: like customer_id)
        -- Set 'customer_id' with 'a_name'.
      do
        customer_id := a_name
      ensure
        customer_id_set: customer_id = a_name
      end

    set_discount_amount (a_name: like discount_amount)
        -- Set 'discount_amount' with 'a_name'.
      do
        discount_amount := a_name
      ensure
        discount_amount_set: discount_amount = a_name
      end

    set_discount_days (a_name: like discount_days)
        -- Set 'discount_days' with 'a_name'.
      do
        discount_days := a_name
      ensure
        discount_days_set: discount_days = a_name
      end

    set_discount_percentage (a_name: like discount_percentage)
        -- Set 'discount_percentage' with 'a_name'.
      do
        discount_percentage := a_name
      ensure
        discount_percentage_set: discount_percentage = a_name
      end

    set_document_type (a_name: like document_type)
        -- Set 'document_type' with 'a_name'.
      do
        document_type := a_name
      ensure
        document_type_set: document_type = a_name
      end

    set_dunning_level (a_name: like dunning_level)
        -- Set 'dunning_level' with 'a_name'.
      do
        dunning_level := a_name
      ensure
        dunning_level_set: dunning_level = a_name
      end

    set_input_vat_amount (a_name: like input_vat_amount)
        -- Set 'input_vat_amount' with 'a_name'.
      do
        input_vat_amount := a_name
      ensure
        input_vat_amount_set: input_vat_amount = a_name
      end

    set_input_vat_deductible (a_name: like input_vat_deductible)
        -- Set 'input_vat_deductible' with 'a_name'.
      do
        input_vat_deductible := a_name
      ensure
        input_vat_deductible_set: input_vat_deductible = a_name
      end

    set_input_vat_percentage (a_name: like input_vat_percentage)
        -- Set 'input_vat_percentage' with 'a_name'.
      do
        input_vat_percentage := a_name
      ensure
        input_vat_percentage_set: input_vat_percentage = a_name
      end

    set_introduction_text (a_name: like introduction_text)
        -- Set 'introduction_text' with 'a_name'.
      do
        introduction_text := a_name
      ensure
        introduction_text_set: introduction_text = a_name
      end

    set_invoice_type (a_name: like invoice_type)
        -- Set 'invoice_type' with 'a_name'.
      do
        invoice_type := a_name
      ensure
        invoice_type_set: invoice_type = a_name
      end

    set_is_cancelled (a_name: like is_cancelled)
        -- Set 'is_cancelled' with 'a_name'.
      do
        is_cancelled := a_name
      ensure
        is_cancelled_set: is_cancelled = a_name
      end

    set_is_draft (a_name: like is_draft)
        -- Set 'is_draft' with 'a_name'.
      do
        is_draft := a_name
      ensure
        is_draft_set: is_draft = a_name
      end

    set_is_eu_acquisition (a_name: like is_eu_acquisition)
        -- Set 'is_eu_acquisition' with 'a_name'.
      do
        is_eu_acquisition := a_name
      ensure
        is_eu_acquisition_set: is_eu_acquisition = a_name
      end

    set_is_eu_delivery (a_name: like is_eu_delivery)
        -- Set 'is_eu_delivery' with 'a_name'.
      do
        is_eu_delivery := a_name
      ensure
        is_eu_delivery_set: is_eu_delivery = a_name
      end

    set_is_intra_community_acquisition (a_name: like is_intra_community_acquisition)
        -- Set 'is_intra_community_acquisition' with 'a_name'.
      do
        is_intra_community_acquisition := a_name
      ensure
        is_intra_community_acquisition_set: is_intra_community_acquisition = a_name
      end

    set_is_reverse_charge (a_name: like is_reverse_charge)
        -- Set 'is_reverse_charge' with 'a_name'.
      do
        is_reverse_charge := a_name
      ensure
        is_reverse_charge_set: is_reverse_charge = a_name
      end

    set_issue_date (a_name: like issue_date)
        -- Set 'issue_date' with 'a_name'.
      do
        issue_date := a_name
      ensure
        issue_date_set: issue_date = a_name
      end

    set_ledger_account (a_name: like ledger_account)
        -- Set 'ledger_account' with 'a_name'.
      do
        ledger_account := a_name
      ensure
        ledger_account_set: ledger_account = a_name
      end

    set_line_items (a_name: like line_items)
        -- Set 'line_items' with 'a_name'.
      do
        line_items := a_name
      ensure
        line_items_set: line_items = a_name
      end

    set_margin25a (a_name: like margin25a)
        -- Set 'margin25a' with 'a_name'.
      do
        margin25a := a_name
      ensure
        margin25a_set: margin25a = a_name
      end

    set_margin25a_gross (a_name: like margin25a_gross)
        -- Set 'margin25a_gross' with 'a_name'.
      do
        margin25a_gross := a_name
      ensure
        margin25a_gross_set: margin25a_gross = a_name
      end

    set_margin25a_purchase_price (a_name: like margin25a_purchase_price)
        -- Set 'margin25a_purchase_price' with 'a_name'.
      do
        margin25a_purchase_price := a_name
      ensure
        margin25a_purchase_price_set: margin25a_purchase_price = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_order_number (a_name: like order_number)
        -- Set 'order_number' with 'a_name'.
      do
        order_number := a_name
      ensure
        order_number_set: order_number = a_name
      end

    set_original_pdf_path (a_name: like original_pdf_path)
        -- Set 'original_pdf_path' with 'a_name'.
      do
        original_pdf_path := a_name
      ensure
        original_pdf_path_set: original_pdf_path = a_name
      end

    set_paid_amount (a_name: like paid_amount)
        -- Set 'paid_amount' with 'a_name'.
      do
        paid_amount := a_name
      ensure
        paid_amount_set: paid_amount = a_name
      end

    set_payment_due_date (a_name: like payment_due_date)
        -- Set 'payment_due_date' with 'a_name'.
      do
        payment_due_date := a_name
      ensure
        payment_due_date_set: payment_due_date = a_name
      end

    set_payment_status (a_name: like payment_status)
        -- Set 'payment_status' with 'a_name'.
      do
        payment_status := a_name
      ensure
        payment_status_set: payment_status = a_name
      end

    set_payment_terms_text (a_name: like payment_terms_text)
        -- Set 'payment_terms_text' with 'a_name'.
      do
        payment_terms_text := a_name
      ensure
        payment_terms_text_set: payment_terms_text = a_name
      end

    set_preceding_sales_voucher_id (a_name: like preceding_sales_voucher_id)
        -- Set 'preceding_sales_voucher_id' with 'a_name'.
      do
        preceding_sales_voucher_id := a_name
      ensure
        preceding_sales_voucher_id_set: preceding_sales_voucher_id = a_name
      end

    set_preceding_sales_voucher_type (a_name: like preceding_sales_voucher_type)
        -- Set 'preceding_sales_voucher_type' with 'a_name'.
      do
        preceding_sales_voucher_type := a_name
      ensure
        preceding_sales_voucher_type_set: preceding_sales_voucher_type = a_name
      end

    set_receipt_confirmation_available (a_name: like receipt_confirmation_available)
        -- Set 'receipt_confirmation_available' with 'a_name'.
      do
        receipt_confirmation_available := a_name
      ensure
        receipt_confirmation_available_set: receipt_confirmation_available = a_name
      end

    set_related_invoice_id (a_name: like related_invoice_id)
        -- Set 'related_invoice_id' with 'a_name'.
      do
        related_invoice_id := a_name
      ensure
        related_invoice_id_set: related_invoice_id = a_name
      end

    set_relationship_type (a_name: like relationship_type)
        -- Set 'relationship_type' with 'a_name'.
      do
        relationship_type := a_name
      ensure
        relationship_type_set: relationship_type = a_name
      end

    set_sender_snapshot (a_name: like sender_snapshot)
        -- Set 'sender_snapshot' with 'a_name'.
      do
        sender_snapshot := a_name
      ensure
        sender_snapshot_set: sender_snapshot = a_name
      end

    set_sent_at (a_name: like sent_at)
        -- Set 'sent_at' with 'a_name'.
      do
        sent_at := a_name
      ensure
        sent_at_set: sent_at = a_name
      end

    set_service_period_end (a_name: like service_period_end)
        -- Set 'service_period_end' with 'a_name'.
      do
        service_period_end := a_name
      ensure
        service_period_end_set: service_period_end = a_name
      end

    set_service_period_start (a_name: like service_period_start)
        -- Set 'service_period_start' with 'a_name'.
      do
        service_period_start := a_name
      ensure
        service_period_start_set: service_period_start = a_name
      end

    set_status (a_name: like status)
        -- Set 'status' with 'a_name'.
      do
        status := a_name
      ensure
        status_set: status = a_name
      end

    set_subtotal (a_name: like subtotal)
        -- Set 'subtotal' with 'a_name'.
      do
        subtotal := a_name
      ensure
        subtotal_set: subtotal = a_name
      end

    set_supplier_id (a_name: like supplier_id)
        -- Set 'supplier_id' with 'a_name'.
      do
        supplier_id := a_name
      ensure
        supplier_id_set: supplier_id = a_name
      end

    set_tax_exemption_reason (a_name: like tax_exemption_reason)
        -- Set 'tax_exemption_reason' with 'a_name'.
      do
        tax_exemption_reason := a_name
      ensure
        tax_exemption_reason_set: tax_exemption_reason = a_name
      end

    set_total_amount (a_name: like total_amount)
        -- Set 'total_amount' with 'a_name'.
      do
        total_amount := a_name
      ensure
        total_amount_set: total_amount = a_name
      end

    set_total_tax (a_name: like total_tax)
        -- Set 'total_tax' with 'a_name'.
      do
        total_tax := a_name
      ensure
        total_tax_set: total_tax = a_name
      end

    set_vat_country (a_name: like vat_country)
        -- Set 'vat_country' with 'a_name'.
      do
        vat_country := a_name
      ensure
        vat_country_set: vat_country = a_name
      end

    set_vat_special_case (a_name: like vat_special_case)
        -- Set 'vat_special_case' with 'a_name'.
      do
        vat_special_case := a_name
      ensure
        vat_special_case_set: vat_special_case = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass INVOICE%N")
        if attached attachments as l_attachments then
          Result.append ("%Nattachments:")
          Result.append (l_attachments.out)
          Result.append ("%N")
        end
        if attached billing_period_end as l_billing_period_end then
          Result.append ("%Nbilling_period_end:")
          Result.append (l_billing_period_end.out)
          Result.append ("%N")
        end
        if attached billing_period_start as l_billing_period_start then
          Result.append ("%Nbilling_period_start:")
          Result.append (l_billing_period_start.out)
          Result.append ("%N")
        end
        if attached cancellation_date as l_cancellation_date then
          Result.append ("%Ncancellation_date:")
          Result.append (l_cancellation_date.out)
          Result.append ("%N")
        end
        if attached cancellation_invoice_id as l_cancellation_invoice_id then
          Result.append ("%Ncancellation_invoice_id:")
          Result.append (l_cancellation_invoice_id.out)
          Result.append ("%N")
        end
        if attached cancellation_reason as l_cancellation_reason then
          Result.append ("%Ncancellation_reason:")
          Result.append (l_cancellation_reason.out)
          Result.append ("%N")
        end
        if attached contract_id as l_contract_id then
          Result.append ("%Ncontract_id:")
          Result.append (l_contract_id.out)
          Result.append ("%N")
        end
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached customer_id as l_customer_id then
          Result.append ("%Ncustomer_id:")
          Result.append (l_customer_id.out)
          Result.append ("%N")
        end
        if attached discount_amount as l_discount_amount then
          Result.append ("%Ndiscount_amount:")
          Result.append (l_discount_amount.out)
          Result.append ("%N")
        end
        if attached discount_days as l_discount_days then
          Result.append ("%Ndiscount_days:")
          Result.append (l_discount_days.out)
          Result.append ("%N")
        end
        if attached discount_percentage as l_discount_percentage then
          Result.append ("%Ndiscount_percentage:")
          Result.append (l_discount_percentage.out)
          Result.append ("%N")
        end
        if attached document_type as l_document_type then
          Result.append ("%Ndocument_type:")
          Result.append (l_document_type.out)
          Result.append ("%N")
        end
        if attached dunning_level as l_dunning_level then
          Result.append ("%Ndunning_level:")
          Result.append (l_dunning_level.out)
          Result.append ("%N")
        end
        if attached input_vat_amount as l_input_vat_amount then
          Result.append ("%Ninput_vat_amount:")
          Result.append (l_input_vat_amount.out)
          Result.append ("%N")
        end
        if attached input_vat_deductible as l_input_vat_deductible then
          Result.append ("%Ninput_vat_deductible:")
          Result.append (l_input_vat_deductible.out)
          Result.append ("%N")
        end
        if attached input_vat_percentage as l_input_vat_percentage then
          Result.append ("%Ninput_vat_percentage:")
          Result.append (l_input_vat_percentage.out)
          Result.append ("%N")
        end
        if attached introduction_text as l_introduction_text then
          Result.append ("%Nintroduction_text:")
          Result.append (l_introduction_text.out)
          Result.append ("%N")
        end
        if attached invoice_type as l_invoice_type then
          Result.append ("%Ninvoice_type:")
          Result.append (l_invoice_type.out)
          Result.append ("%N")
        end
        if attached is_cancelled as l_is_cancelled then
          Result.append ("%Nis_cancelled:")
          Result.append (l_is_cancelled.out)
          Result.append ("%N")
        end
        if attached is_draft as l_is_draft then
          Result.append ("%Nis_draft:")
          Result.append (l_is_draft.out)
          Result.append ("%N")
        end
        if attached is_eu_acquisition as l_is_eu_acquisition then
          Result.append ("%Nis_eu_acquisition:")
          Result.append (l_is_eu_acquisition.out)
          Result.append ("%N")
        end
        if attached is_eu_delivery as l_is_eu_delivery then
          Result.append ("%Nis_eu_delivery:")
          Result.append (l_is_eu_delivery.out)
          Result.append ("%N")
        end
        if attached is_intra_community_acquisition as l_is_intra_community_acquisition then
          Result.append ("%Nis_intra_community_acquisition:")
          Result.append (l_is_intra_community_acquisition.out)
          Result.append ("%N")
        end
        if attached is_reverse_charge as l_is_reverse_charge then
          Result.append ("%Nis_reverse_charge:")
          Result.append (l_is_reverse_charge.out)
          Result.append ("%N")
        end
        if attached issue_date as l_issue_date then
          Result.append ("%Nissue_date:")
          Result.append (l_issue_date.out)
          Result.append ("%N")
        end
        if attached ledger_account as l_ledger_account then
          Result.append ("%Nledger_account:")
          Result.append (l_ledger_account.out)
          Result.append ("%N")
        end
        if attached line_items as l_line_items then
          Result.append ("%Nline_items:")
          Result.append (l_line_items.out)
          Result.append ("%N")
        end
        if attached margin25a as l_margin25a then
          Result.append ("%Nmargin25a:")
          Result.append (l_margin25a.out)
          Result.append ("%N")
        end
        if attached margin25a_gross as l_margin25a_gross then
          Result.append ("%Nmargin25a_gross:")
          Result.append (l_margin25a_gross.out)
          Result.append ("%N")
        end
        if attached margin25a_purchase_price as l_margin25a_purchase_price then
          Result.append ("%Nmargin25a_purchase_price:")
          Result.append (l_margin25a_purchase_price.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached order_number as l_order_number then
          Result.append ("%Norder_number:")
          Result.append (l_order_number.out)
          Result.append ("%N")
        end
        if attached original_pdf_path as l_original_pdf_path then
          Result.append ("%Noriginal_pdf_path:")
          Result.append (l_original_pdf_path.out)
          Result.append ("%N")
        end
        if attached paid_amount as l_paid_amount then
          Result.append ("%Npaid_amount:")
          Result.append (l_paid_amount.out)
          Result.append ("%N")
        end
        if attached payment_due_date as l_payment_due_date then
          Result.append ("%Npayment_due_date:")
          Result.append (l_payment_due_date.out)
          Result.append ("%N")
        end
        if attached payment_status as l_payment_status then
          Result.append ("%Npayment_status:")
          Result.append (l_payment_status.out)
          Result.append ("%N")
        end
        if attached payment_terms_text as l_payment_terms_text then
          Result.append ("%Npayment_terms_text:")
          Result.append (l_payment_terms_text.out)
          Result.append ("%N")
        end
        if attached preceding_sales_voucher_id as l_preceding_sales_voucher_id then
          Result.append ("%Npreceding_sales_voucher_id:")
          Result.append (l_preceding_sales_voucher_id.out)
          Result.append ("%N")
        end
        if attached preceding_sales_voucher_type as l_preceding_sales_voucher_type then
          Result.append ("%Npreceding_sales_voucher_type:")
          Result.append (l_preceding_sales_voucher_type.out)
          Result.append ("%N")
        end
        if attached receipt_confirmation_available as l_receipt_confirmation_available then
          Result.append ("%Nreceipt_confirmation_available:")
          Result.append (l_receipt_confirmation_available.out)
          Result.append ("%N")
        end
        if attached related_invoice_id as l_related_invoice_id then
          Result.append ("%Nrelated_invoice_id:")
          Result.append (l_related_invoice_id.out)
          Result.append ("%N")
        end
        if attached relationship_type as l_relationship_type then
          Result.append ("%Nrelationship_type:")
          Result.append (l_relationship_type.out)
          Result.append ("%N")
        end
        if attached sender_snapshot as l_sender_snapshot then
          Result.append ("%Nsender_snapshot:")
          Result.append (l_sender_snapshot.out)
          Result.append ("%N")
        end
        if attached sent_at as l_sent_at then
          Result.append ("%Nsent_at:")
          Result.append (l_sent_at.out)
          Result.append ("%N")
        end
        if attached service_period_end as l_service_period_end then
          Result.append ("%Nservice_period_end:")
          Result.append (l_service_period_end.out)
          Result.append ("%N")
        end
        if attached service_period_start as l_service_period_start then
          Result.append ("%Nservice_period_start:")
          Result.append (l_service_period_start.out)
          Result.append ("%N")
        end
        if attached status as l_status then
          Result.append ("%Nstatus:")
          Result.append (l_status.out)
          Result.append ("%N")
        end
        if attached subtotal as l_subtotal then
          Result.append ("%Nsubtotal:")
          Result.append (l_subtotal.out)
          Result.append ("%N")
        end
        if attached supplier_id as l_supplier_id then
          Result.append ("%Nsupplier_id:")
          Result.append (l_supplier_id.out)
          Result.append ("%N")
        end
        if attached tax_exemption_reason as l_tax_exemption_reason then
          Result.append ("%Ntax_exemption_reason:")
          Result.append (l_tax_exemption_reason.out)
          Result.append ("%N")
        end
        if attached total_amount as l_total_amount then
          Result.append ("%Ntotal_amount:")
          Result.append (l_total_amount.out)
          Result.append ("%N")
        end
        if attached total_tax as l_total_tax then
          Result.append ("%Ntotal_tax:")
          Result.append (l_total_tax.out)
          Result.append ("%N")
        end
        if attached vat_country as l_vat_country then
          Result.append ("%Nvat_country:")
          Result.append (l_vat_country.out)
          Result.append ("%N")
        end
        if attached vat_special_case as l_vat_special_case then
          Result.append ("%Nvat_special_case:")
          Result.append (l_vat_special_case.out)
          Result.append ("%N")
        end
      end
end

