note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class KST_ERGEBNIS




feature --Access

    gesamt: detachable STRING_32
      
    gesamtbelastung: detachable STRING_32
      
    gewerbesteuer: detachable STRING_32
      
    gewinn: detachable STRING_32
      
    ist_kapitalgesellschaft: BOOLEAN
      
    jahr: INTEGER_32
      
    koerperschaftsteuer: detachable STRING_32
      
    solidaritaetszuschlag: detachable STRING_32
      

feature -- Change Element

    set_gesamt (a_name: like gesamt)
        -- Set 'gesamt' with 'a_name'.
      do
        gesamt := a_name
      ensure
        gesamt_set: gesamt = a_name
      end

    set_gesamtbelastung (a_name: like gesamtbelastung)
        -- Set 'gesamtbelastung' with 'a_name'.
      do
        gesamtbelastung := a_name
      ensure
        gesamtbelastung_set: gesamtbelastung = a_name
      end

    set_gewerbesteuer (a_name: like gewerbesteuer)
        -- Set 'gewerbesteuer' with 'a_name'.
      do
        gewerbesteuer := a_name
      ensure
        gewerbesteuer_set: gewerbesteuer = a_name
      end

    set_gewinn (a_name: like gewinn)
        -- Set 'gewinn' with 'a_name'.
      do
        gewinn := a_name
      ensure
        gewinn_set: gewinn = a_name
      end

    set_ist_kapitalgesellschaft (a_name: like ist_kapitalgesellschaft)
        -- Set 'ist_kapitalgesellschaft' with 'a_name'.
      do
        ist_kapitalgesellschaft := a_name
      ensure
        ist_kapitalgesellschaft_set: ist_kapitalgesellschaft = a_name
      end

    set_jahr (a_name: like jahr)
        -- Set 'jahr' with 'a_name'.
      do
        jahr := a_name
      ensure
        jahr_set: jahr = a_name
      end

    set_koerperschaftsteuer (a_name: like koerperschaftsteuer)
        -- Set 'koerperschaftsteuer' with 'a_name'.
      do
        koerperschaftsteuer := a_name
      ensure
        koerperschaftsteuer_set: koerperschaftsteuer = a_name
      end

    set_solidaritaetszuschlag (a_name: like solidaritaetszuschlag)
        -- Set 'solidaritaetszuschlag' with 'a_name'.
      do
        solidaritaetszuschlag := a_name
      ensure
        solidaritaetszuschlag_set: solidaritaetszuschlag = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass KST_ERGEBNIS%N")
        if attached gesamt as l_gesamt then
          Result.append ("%Ngesamt:")
          Result.append (l_gesamt.out)
          Result.append ("%N")
        end
        if attached gesamtbelastung as l_gesamtbelastung then
          Result.append ("%Ngesamtbelastung:")
          Result.append (l_gesamtbelastung.out)
          Result.append ("%N")
        end
        if attached gewerbesteuer as l_gewerbesteuer then
          Result.append ("%Ngewerbesteuer:")
          Result.append (l_gewerbesteuer.out)
          Result.append ("%N")
        end
        if attached gewinn as l_gewinn then
          Result.append ("%Ngewinn:")
          Result.append (l_gewinn.out)
          Result.append ("%N")
        end
        if attached ist_kapitalgesellschaft as l_ist_kapitalgesellschaft then
          Result.append ("%Nist_kapitalgesellschaft:")
          Result.append (l_ist_kapitalgesellschaft.out)
          Result.append ("%N")
        end
        if attached jahr as l_jahr then
          Result.append ("%Njahr:")
          Result.append (l_jahr.out)
          Result.append ("%N")
        end
        if attached koerperschaftsteuer as l_koerperschaftsteuer then
          Result.append ("%Nkoerperschaftsteuer:")
          Result.append (l_koerperschaftsteuer.out)
          Result.append ("%N")
        end
        if attached solidaritaetszuschlag as l_solidaritaetszuschlag then
          Result.append ("%Nsolidaritaetszuschlag:")
          Result.append (l_solidaritaetszuschlag.out)
          Result.append ("%N")
        end
      end
end

