note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class KYC_RECORD




feature --Access

    customer_id: detachable STRING_32
      -- Referenz auf den Kunden/Kontakt.
    customer_name: detachable STRING_32
      -- Name des Kunden (für die Suche).
    kyc_date: detachable DATE
      -- Datum der KYC-Prüfung (GwG § 8).
    notes: detachable STRING_32
      -- Freitext-Notizen.
    retention_until: detachable DATE
      -- Aufbewahrungsfrist (GwG § 8 Abs. 4: 5 Jahre).
    risk_assessment: detachable STRING_32
      -- Risikoeinschätzung (z. B. Risikoklasse).

feature -- Change Element

    set_customer_id (a_name: like customer_id)
        -- Set 'customer_id' with 'a_name'.
      do
        customer_id := a_name
      ensure
        customer_id_set: customer_id = a_name
      end

    set_customer_name (a_name: like customer_name)
        -- Set 'customer_name' with 'a_name'.
      do
        customer_name := a_name
      ensure
        customer_name_set: customer_name = a_name
      end

    set_kyc_date (a_name: like kyc_date)
        -- Set 'kyc_date' with 'a_name'.
      do
        kyc_date := a_name
      ensure
        kyc_date_set: kyc_date = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_retention_until (a_name: like retention_until)
        -- Set 'retention_until' with 'a_name'.
      do
        retention_until := a_name
      ensure
        retention_until_set: retention_until = a_name
      end

    set_risk_assessment (a_name: like risk_assessment)
        -- Set 'risk_assessment' with 'a_name'.
      do
        risk_assessment := a_name
      ensure
        risk_assessment_set: risk_assessment = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass KYC_RECORD%N")
        if attached customer_id as l_customer_id then
          Result.append ("%Ncustomer_id:")
          Result.append (l_customer_id.out)
          Result.append ("%N")
        end
        if attached customer_name as l_customer_name then
          Result.append ("%Ncustomer_name:")
          Result.append (l_customer_name.out)
          Result.append ("%N")
        end
        if attached kyc_date as l_kyc_date then
          Result.append ("%Nkyc_date:")
          Result.append (l_kyc_date.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached retention_until as l_retention_until then
          Result.append ("%Nretention_until:")
          Result.append (l_retention_until.out)
          Result.append ("%N")
        end
        if attached risk_assessment as l_risk_assessment then
          Result.append ("%Nrisk_assessment:")
          Result.append (l_risk_assessment.out)
          Result.append ("%N")
        end
      end
end

