note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class LEGAL_DOCUMENT_RESET




feature --Access

    doc_type: detachable STRING_32
      
    lang: detachable STRING_32
      

feature -- Change Element

    set_doc_type (a_name: like doc_type)
        -- Set 'doc_type' with 'a_name'.
      do
        doc_type := a_name
      ensure
        doc_type_set: doc_type = a_name
      end

    set_lang (a_name: like lang)
        -- Set 'lang' with 'a_name'.
      do
        lang := a_name
      ensure
        lang_set: lang = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass LEGAL_DOCUMENT_RESET%N")
        if attached doc_type as l_doc_type then
          Result.append ("%Ndoc_type:")
          Result.append (l_doc_type.out)
          Result.append ("%N")
        end
        if attached lang as l_lang then
          Result.append ("%Nlang:")
          Result.append (l_lang.out)
          Result.append ("%N")
        end
      end
end

