note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class MARKETPLACE_WEBHOOK_EVENT




feature --Access

    connection_id: detachable STRING_32
      -- References the marketplace connection entity.
    event_body: detachable ANY
      
    event_type: detachable STRING_32
      
    headers: detachable ANY
      
    platform: detachable STRING_32
      
    processed: BOOLEAN
      
    processing_error: detachable STRING_32
      

feature -- Change Element

    set_connection_id (a_name: like connection_id)
        -- Set 'connection_id' with 'a_name'.
      do
        connection_id := a_name
      ensure
        connection_id_set: connection_id = a_name
      end

    set_event_body (a_name: like event_body)
        -- Set 'event_body' with 'a_name'.
      do
        event_body := a_name
      ensure
        event_body_set: event_body = a_name
      end

    set_event_type (a_name: like event_type)
        -- Set 'event_type' with 'a_name'.
      do
        event_type := a_name
      ensure
        event_type_set: event_type = a_name
      end

    set_headers (a_name: like headers)
        -- Set 'headers' with 'a_name'.
      do
        headers := a_name
      ensure
        headers_set: headers = a_name
      end

    set_platform (a_name: like platform)
        -- Set 'platform' with 'a_name'.
      do
        platform := a_name
      ensure
        platform_set: platform = a_name
      end

    set_processed (a_name: like processed)
        -- Set 'processed' with 'a_name'.
      do
        processed := a_name
      ensure
        processed_set: processed = a_name
      end

    set_processing_error (a_name: like processing_error)
        -- Set 'processing_error' with 'a_name'.
      do
        processing_error := a_name
      ensure
        processing_error_set: processing_error = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass MARKETPLACE_WEBHOOK_EVENT%N")
        if attached connection_id as l_connection_id then
          Result.append ("%Nconnection_id:")
          Result.append (l_connection_id.out)
          Result.append ("%N")
        end
        if attached event_body as l_event_body then
          Result.append ("%Nevent_body:")
          Result.append (l_event_body.out)
          Result.append ("%N")
        end
        if attached event_type as l_event_type then
          Result.append ("%Nevent_type:")
          Result.append (l_event_type.out)
          Result.append ("%N")
        end
        if attached headers as l_headers then
          Result.append ("%Nheaders:")
          Result.append (l_headers.out)
          Result.append ("%N")
        end
        if attached platform as l_platform then
          Result.append ("%Nplatform:")
          Result.append (l_platform.out)
          Result.append ("%N")
        end
        if attached processed as l_processed then
          Result.append ("%Nprocessed:")
          Result.append (l_processed.out)
          Result.append ("%N")
        end
        if attached processing_error as l_processing_error then
          Result.append ("%Nprocessing_error:")
          Result.append (l_processing_error.out)
          Result.append ("%N")
        end
      end
end

