note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class OCR_TEXT_REQUEST




feature --Access

    ocr_text: detachable STRING_32
      

feature -- Change Element

    set_ocr_text (a_name: like ocr_text)
        -- Set 'ocr_text' with 'a_name'.
      do
        ocr_text := a_name
      ensure
        ocr_text_set: ocr_text = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass OCR_TEXT_REQUEST%N")
        if attached ocr_text as l_ocr_text then
          Result.append ("%Nocr_text:")
          Result.append (l_ocr_text.out)
          Result.append ("%N")
        end
      end
end

