note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class OFFENLEGUNG_REPORT




feature --Access

    deadline: detachable DATE
      -- Fristende (Abschlussstichtag + Frist).
    deadline_months: INTEGER_32
      -- Offenlegungsfrist in Monaten (§ 325 Abs. 4 HGB).
    items: detachable LIST [OFFENLEGUNG_ITEM]
      
    kapitalmarktorientiert: BOOLEAN
      -- Annahme über die Kapitalmarktorientierung.
    var_note: detachable STRING_32
      
    year: INTEGER_32
      -- Berichtsjahr (laufendes Kalenderjahr).

feature -- Change Element

    set_deadline (a_name: like deadline)
        -- Set 'deadline' with 'a_name'.
      do
        deadline := a_name
      ensure
        deadline_set: deadline = a_name
      end

    set_deadline_months (a_name: like deadline_months)
        -- Set 'deadline_months' with 'a_name'.
      do
        deadline_months := a_name
      ensure
        deadline_months_set: deadline_months = a_name
      end

    set_items (a_name: like items)
        -- Set 'items' with 'a_name'.
      do
        items := a_name
      ensure
        items_set: items = a_name
      end

    set_kapitalmarktorientiert (a_name: like kapitalmarktorientiert)
        -- Set 'kapitalmarktorientiert' with 'a_name'.
      do
        kapitalmarktorientiert := a_name
      ensure
        kapitalmarktorientiert_set: kapitalmarktorientiert = a_name
      end

    set_var_note (a_name: like var_note)
        -- Set 'var_note' with 'a_name'.
      do
        var_note := a_name
      ensure
        var_note_set: var_note = a_name
      end

    set_year (a_name: like year)
        -- Set 'year' with 'a_name'.
      do
        year := a_name
      ensure
        year_set: year = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass OFFENLEGUNG_REPORT%N")
        if attached deadline as l_deadline then
          Result.append ("%Ndeadline:")
          Result.append (l_deadline.out)
          Result.append ("%N")
        end
        if attached deadline_months as l_deadline_months then
          Result.append ("%Ndeadline_months:")
          Result.append (l_deadline_months.out)
          Result.append ("%N")
        end
        if attached items as l_items then
          across l_items as ic loop
            Result.append ("%N items:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached kapitalmarktorientiert as l_kapitalmarktorientiert then
          Result.append ("%Nkapitalmarktorientiert:")
          Result.append (l_kapitalmarktorientiert.out)
          Result.append ("%N")
        end
        if attached var_note as l_var_note then
          Result.append ("%Nvar_note:")
          Result.append (l_var_note.out)
          Result.append ("%N")
        end
        if attached year as l_year then
          Result.append ("%Nyear:")
          Result.append (l_year.out)
          Result.append ("%N")
        end
      end
end

