note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class ORDER_UPDATE




feature --Access

    audit_log: detachable ANY
      
    currency: detachable STRING_32
      
    customer_id: detachable STRING_32
      -- References the customer entity.
    external_reference: detachable STRING_32
      
    invoice_address: detachable ANY
      
    items: detachable ANY
      
    language: detachable LANGUAGE_CODE
      
    order_status: detachable ORDER_STATUS
      
    payment_method: detachable PAYMENT_METHOD
      
    shipping_address: detachable ANY
      
    shipping_cost: detachable STRING_32
      
    shipping_method: detachable STRING_32
      
    shipping_weight: detachable STRING_32
      
    tags: detachable LIST [STRING_32]
      
    total_cost: detachable STRING_32
      

feature -- Change Element

    set_audit_log (a_name: like audit_log)
        -- Set 'audit_log' with 'a_name'.
      do
        audit_log := a_name
      ensure
        audit_log_set: audit_log = a_name
      end

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_customer_id (a_name: like customer_id)
        -- Set 'customer_id' with 'a_name'.
      do
        customer_id := a_name
      ensure
        customer_id_set: customer_id = a_name
      end

    set_external_reference (a_name: like external_reference)
        -- Set 'external_reference' with 'a_name'.
      do
        external_reference := a_name
      ensure
        external_reference_set: external_reference = a_name
      end

    set_invoice_address (a_name: like invoice_address)
        -- Set 'invoice_address' with 'a_name'.
      do
        invoice_address := a_name
      ensure
        invoice_address_set: invoice_address = a_name
      end

    set_items (a_name: like items)
        -- Set 'items' with 'a_name'.
      do
        items := a_name
      ensure
        items_set: items = a_name
      end

    set_language (a_name: like language)
        -- Set 'language' with 'a_name'.
      do
        language := a_name
      ensure
        language_set: language = a_name
      end

    set_order_status (a_name: like order_status)
        -- Set 'order_status' with 'a_name'.
      do
        order_status := a_name
      ensure
        order_status_set: order_status = a_name
      end

    set_payment_method (a_name: like payment_method)
        -- Set 'payment_method' with 'a_name'.
      do
        payment_method := a_name
      ensure
        payment_method_set: payment_method = a_name
      end

    set_shipping_address (a_name: like shipping_address)
        -- Set 'shipping_address' with 'a_name'.
      do
        shipping_address := a_name
      ensure
        shipping_address_set: shipping_address = a_name
      end

    set_shipping_cost (a_name: like shipping_cost)
        -- Set 'shipping_cost' with 'a_name'.
      do
        shipping_cost := a_name
      ensure
        shipping_cost_set: shipping_cost = a_name
      end

    set_shipping_method (a_name: like shipping_method)
        -- Set 'shipping_method' with 'a_name'.
      do
        shipping_method := a_name
      ensure
        shipping_method_set: shipping_method = a_name
      end

    set_shipping_weight (a_name: like shipping_weight)
        -- Set 'shipping_weight' with 'a_name'.
      do
        shipping_weight := a_name
      ensure
        shipping_weight_set: shipping_weight = a_name
      end

    set_tags (a_name: like tags)
        -- Set 'tags' with 'a_name'.
      do
        tags := a_name
      ensure
        tags_set: tags = a_name
      end

    set_total_cost (a_name: like total_cost)
        -- Set 'total_cost' with 'a_name'.
      do
        total_cost := a_name
      ensure
        total_cost_set: total_cost = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass ORDER_UPDATE%N")
        if attached audit_log as l_audit_log then
          Result.append ("%Naudit_log:")
          Result.append (l_audit_log.out)
          Result.append ("%N")
        end
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached customer_id as l_customer_id then
          Result.append ("%Ncustomer_id:")
          Result.append (l_customer_id.out)
          Result.append ("%N")
        end
        if attached external_reference as l_external_reference then
          Result.append ("%Nexternal_reference:")
          Result.append (l_external_reference.out)
          Result.append ("%N")
        end
        if attached invoice_address as l_invoice_address then
          Result.append ("%Ninvoice_address:")
          Result.append (l_invoice_address.out)
          Result.append ("%N")
        end
        if attached items as l_items then
          Result.append ("%Nitems:")
          Result.append (l_items.out)
          Result.append ("%N")
        end
        if attached language as l_language then
          Result.append ("%Nlanguage:")
          Result.append (l_language.out)
          Result.append ("%N")
        end
        if attached order_status as l_order_status then
          Result.append ("%Norder_status:")
          Result.append (l_order_status.out)
          Result.append ("%N")
        end
        if attached payment_method as l_payment_method then
          Result.append ("%Npayment_method:")
          Result.append (l_payment_method.out)
          Result.append ("%N")
        end
        if attached shipping_address as l_shipping_address then
          Result.append ("%Nshipping_address:")
          Result.append (l_shipping_address.out)
          Result.append ("%N")
        end
        if attached shipping_cost as l_shipping_cost then
          Result.append ("%Nshipping_cost:")
          Result.append (l_shipping_cost.out)
          Result.append ("%N")
        end
        if attached shipping_method as l_shipping_method then
          Result.append ("%Nshipping_method:")
          Result.append (l_shipping_method.out)
          Result.append ("%N")
        end
        if attached shipping_weight as l_shipping_weight then
          Result.append ("%Nshipping_weight:")
          Result.append (l_shipping_weight.out)
          Result.append ("%N")
        end
        if attached tags as l_tags then
          across l_tags as ic loop
            Result.append ("%N tags:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_cost as l_total_cost then
          Result.append ("%Ntotal_cost:")
          Result.append (l_total_cost.out)
          Result.append ("%N")
        end
      end
end

