note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class OSS_REPORT




feature --Access

    dependencies: detachable LIST [OSS_DEPENDENCY]
      
    total_count: INTEGER_32
      

feature -- Change Element

    set_dependencies (a_name: like dependencies)
        -- Set 'dependencies' with 'a_name'.
      do
        dependencies := a_name
      ensure
        dependencies_set: dependencies = a_name
      end

    set_total_count (a_name: like total_count)
        -- Set 'total_count' with 'a_name'.
      do
        total_count := a_name
      ensure
        total_count_set: total_count = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass OSS_REPORT%N")
        if attached dependencies as l_dependencies then
          across l_dependencies as ic loop
            Result.append ("%N dependencies:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_count as l_total_count then
          Result.append ("%Ntotal_count:")
          Result.append (l_total_count.out)
          Result.append ("%N")
        end
      end
end

