note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class PLUGIN_ERROR_ONE_OF_3




feature --Access

    internal_error: detachable LIST [ANY]
      

feature -- Change Element

    set_internal_error (a_name: like internal_error)
        -- Set 'internal_error' with 'a_name'.
      do
        internal_error := a_name
      ensure
        internal_error_set: internal_error = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass PLUGIN_ERROR_ONE_OF_3%N")
        if attached internal_error as l_internal_error then
          across l_internal_error as ic loop
            Result.append ("%N internal_error:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
      end
end

