note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class PUBLIC_DELIVERY_APPOINTMENT_REQUEST




feature --Access

    email: detachable STRING_32
      
    notes: detachable STRING_32
      
    requested_date: detachable DATE
      
    supplier_name: detachable STRING_32
      
    time_slot: detachable STRING_32
      
    warehouse_code: detachable STRING_32
      -- Warehouse `code` — the supplier does not know the warehouse uuid.

feature -- Change Element

    set_email (a_name: like email)
        -- Set 'email' with 'a_name'.
      do
        email := a_name
      ensure
        email_set: email = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_requested_date (a_name: like requested_date)
        -- Set 'requested_date' with 'a_name'.
      do
        requested_date := a_name
      ensure
        requested_date_set: requested_date = a_name
      end

    set_supplier_name (a_name: like supplier_name)
        -- Set 'supplier_name' with 'a_name'.
      do
        supplier_name := a_name
      ensure
        supplier_name_set: supplier_name = a_name
      end

    set_time_slot (a_name: like time_slot)
        -- Set 'time_slot' with 'a_name'.
      do
        time_slot := a_name
      ensure
        time_slot_set: time_slot = a_name
      end

    set_warehouse_code (a_name: like warehouse_code)
        -- Set 'warehouse_code' with 'a_name'.
      do
        warehouse_code := a_name
      ensure
        warehouse_code_set: warehouse_code = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass PUBLIC_DELIVERY_APPOINTMENT_REQUEST%N")
        if attached email as l_email then
          Result.append ("%Nemail:")
          Result.append (l_email.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached requested_date as l_requested_date then
          Result.append ("%Nrequested_date:")
          Result.append (l_requested_date.out)
          Result.append ("%N")
        end
        if attached supplier_name as l_supplier_name then
          Result.append ("%Nsupplier_name:")
          Result.append (l_supplier_name.out)
          Result.append ("%N")
        end
        if attached time_slot as l_time_slot then
          Result.append ("%Ntime_slot:")
          Result.append (l_time_slot.out)
          Result.append ("%N")
        end
        if attached warehouse_code as l_warehouse_code then
          Result.append ("%Nwarehouse_code:")
          Result.append (l_warehouse_code.out)
          Result.append ("%N")
        end
      end
end

