note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class PUBLIC_RETURN_REQUEST




feature --Access

    email: detachable STRING_32
      
    items: detachable LIST [PUBLIC_RETURN_ITEM]
      
    notes: detachable STRING_32
      
    order_number: detachable STRING_32
      

feature -- Change Element

    set_email (a_name: like email)
        -- Set 'email' with 'a_name'.
      do
        email := a_name
      ensure
        email_set: email = a_name
      end

    set_items (a_name: like items)
        -- Set 'items' with 'a_name'.
      do
        items := a_name
      ensure
        items_set: items = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_order_number (a_name: like order_number)
        -- Set 'order_number' with 'a_name'.
      do
        order_number := a_name
      ensure
        order_number_set: order_number = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass PUBLIC_RETURN_REQUEST%N")
        if attached email as l_email then
          Result.append ("%Nemail:")
          Result.append (l_email.out)
          Result.append ("%N")
        end
        if attached items as l_items then
          across l_items as ic loop
            Result.append ("%N items:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached order_number as l_order_number then
          Result.append ("%Norder_number:")
          Result.append (l_order_number.out)
          Result.append ("%N")
        end
      end
end

