note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class PURCHASE_ORDER_UPDATE




feature --Access

    currency: detachable STRING_32
      
    delivery_address: detachable ANY
      
    expected_delivery_date: detachable DATE
      
    line_items: detachable ANY
      -- JSON array of `{product_id, name, quantity, unit_price_net, tax_rate, delivery_date}`.
    notes: detachable STRING_32
      
    order_date: detachable DATE
      
    po_number: detachable STRING_32
      
    status: detachable PURCHASE_ORDER_STATUS
      -- One of: draft | ordered | partially_received | received | cancelled
    supplier_contact_id: detachable STRING_32
      -- References the supplier entity.
    supplier_name: detachable STRING_32
      
    total_gross_amount: detachable STRING_32
      
    total_net_amount: detachable STRING_32
      

feature -- Change Element

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_delivery_address (a_name: like delivery_address)
        -- Set 'delivery_address' with 'a_name'.
      do
        delivery_address := a_name
      ensure
        delivery_address_set: delivery_address = a_name
      end

    set_expected_delivery_date (a_name: like expected_delivery_date)
        -- Set 'expected_delivery_date' with 'a_name'.
      do
        expected_delivery_date := a_name
      ensure
        expected_delivery_date_set: expected_delivery_date = a_name
      end

    set_line_items (a_name: like line_items)
        -- Set 'line_items' with 'a_name'.
      do
        line_items := a_name
      ensure
        line_items_set: line_items = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_order_date (a_name: like order_date)
        -- Set 'order_date' with 'a_name'.
      do
        order_date := a_name
      ensure
        order_date_set: order_date = a_name
      end

    set_po_number (a_name: like po_number)
        -- Set 'po_number' with 'a_name'.
      do
        po_number := a_name
      ensure
        po_number_set: po_number = a_name
      end

    set_status (a_name: like status)
        -- Set 'status' with 'a_name'.
      do
        status := a_name
      ensure
        status_set: status = a_name
      end

    set_supplier_contact_id (a_name: like supplier_contact_id)
        -- Set 'supplier_contact_id' with 'a_name'.
      do
        supplier_contact_id := a_name
      ensure
        supplier_contact_id_set: supplier_contact_id = a_name
      end

    set_supplier_name (a_name: like supplier_name)
        -- Set 'supplier_name' with 'a_name'.
      do
        supplier_name := a_name
      ensure
        supplier_name_set: supplier_name = a_name
      end

    set_total_gross_amount (a_name: like total_gross_amount)
        -- Set 'total_gross_amount' with 'a_name'.
      do
        total_gross_amount := a_name
      ensure
        total_gross_amount_set: total_gross_amount = a_name
      end

    set_total_net_amount (a_name: like total_net_amount)
        -- Set 'total_net_amount' with 'a_name'.
      do
        total_net_amount := a_name
      ensure
        total_net_amount_set: total_net_amount = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass PURCHASE_ORDER_UPDATE%N")
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached delivery_address as l_delivery_address then
          Result.append ("%Ndelivery_address:")
          Result.append (l_delivery_address.out)
          Result.append ("%N")
        end
        if attached expected_delivery_date as l_expected_delivery_date then
          Result.append ("%Nexpected_delivery_date:")
          Result.append (l_expected_delivery_date.out)
          Result.append ("%N")
        end
        if attached line_items as l_line_items then
          Result.append ("%Nline_items:")
          Result.append (l_line_items.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached order_date as l_order_date then
          Result.append ("%Norder_date:")
          Result.append (l_order_date.out)
          Result.append ("%N")
        end
        if attached po_number as l_po_number then
          Result.append ("%Npo_number:")
          Result.append (l_po_number.out)
          Result.append ("%N")
        end
        if attached status as l_status then
          Result.append ("%Nstatus:")
          Result.append (l_status.out)
          Result.append ("%N")
        end
        if attached supplier_contact_id as l_supplier_contact_id then
          Result.append ("%Nsupplier_contact_id:")
          Result.append (l_supplier_contact_id.out)
          Result.append ("%N")
        end
        if attached supplier_name as l_supplier_name then
          Result.append ("%Nsupplier_name:")
          Result.append (l_supplier_name.out)
          Result.append ("%N")
        end
        if attached total_gross_amount as l_total_gross_amount then
          Result.append ("%Ntotal_gross_amount:")
          Result.append (l_total_gross_amount.out)
          Result.append ("%N")
        end
        if attached total_net_amount as l_total_net_amount then
          Result.append ("%Ntotal_net_amount:")
          Result.append (l_total_net_amount.out)
          Result.append ("%N")
        end
      end
end

