note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class QUOTATION_CREATE




feature --Access

    address: detachable ANY
      
    contact_id: detachable STRING_32
      -- References the contact entity.
    contact_name: detachable STRING_32
      
    currency: detachable STRING_32
      
    expiration_date: detachable DATE
      
    files: detachable ANY
      
    introduction: detachable STRING_32
      
    line_items: detachable ANY
      
    preceding_sales_voucher_id: detachable STRING_32
      -- References the preceding sales voucher entity.
    preceding_sales_voucher_type: detachable PRECEDING_SALES_VOUCHER_TYPE
      
    quotation_number: detachable STRING_32
      
    remark: detachable STRING_32
      
    tax_condition: detachable STRING_32
      
    title: detachable STRING_32
      
    voucher_date: detachable DATE
      
    voucher_status: detachable VOUCHER_STATUS
      

feature -- Change Element

    set_address (a_name: like address)
        -- Set 'address' with 'a_name'.
      do
        address := a_name
      ensure
        address_set: address = a_name
      end

    set_contact_id (a_name: like contact_id)
        -- Set 'contact_id' with 'a_name'.
      do
        contact_id := a_name
      ensure
        contact_id_set: contact_id = a_name
      end

    set_contact_name (a_name: like contact_name)
        -- Set 'contact_name' with 'a_name'.
      do
        contact_name := a_name
      ensure
        contact_name_set: contact_name = a_name
      end

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_expiration_date (a_name: like expiration_date)
        -- Set 'expiration_date' with 'a_name'.
      do
        expiration_date := a_name
      ensure
        expiration_date_set: expiration_date = a_name
      end

    set_files (a_name: like files)
        -- Set 'files' with 'a_name'.
      do
        files := a_name
      ensure
        files_set: files = a_name
      end

    set_introduction (a_name: like introduction)
        -- Set 'introduction' with 'a_name'.
      do
        introduction := a_name
      ensure
        introduction_set: introduction = a_name
      end

    set_line_items (a_name: like line_items)
        -- Set 'line_items' with 'a_name'.
      do
        line_items := a_name
      ensure
        line_items_set: line_items = a_name
      end

    set_preceding_sales_voucher_id (a_name: like preceding_sales_voucher_id)
        -- Set 'preceding_sales_voucher_id' with 'a_name'.
      do
        preceding_sales_voucher_id := a_name
      ensure
        preceding_sales_voucher_id_set: preceding_sales_voucher_id = a_name
      end

    set_preceding_sales_voucher_type (a_name: like preceding_sales_voucher_type)
        -- Set 'preceding_sales_voucher_type' with 'a_name'.
      do
        preceding_sales_voucher_type := a_name
      ensure
        preceding_sales_voucher_type_set: preceding_sales_voucher_type = a_name
      end

    set_quotation_number (a_name: like quotation_number)
        -- Set 'quotation_number' with 'a_name'.
      do
        quotation_number := a_name
      ensure
        quotation_number_set: quotation_number = a_name
      end

    set_remark (a_name: like remark)
        -- Set 'remark' with 'a_name'.
      do
        remark := a_name
      ensure
        remark_set: remark = a_name
      end

    set_tax_condition (a_name: like tax_condition)
        -- Set 'tax_condition' with 'a_name'.
      do
        tax_condition := a_name
      ensure
        tax_condition_set: tax_condition = a_name
      end

    set_title (a_name: like title)
        -- Set 'title' with 'a_name'.
      do
        title := a_name
      ensure
        title_set: title = a_name
      end

    set_voucher_date (a_name: like voucher_date)
        -- Set 'voucher_date' with 'a_name'.
      do
        voucher_date := a_name
      ensure
        voucher_date_set: voucher_date = a_name
      end

    set_voucher_status (a_name: like voucher_status)
        -- Set 'voucher_status' with 'a_name'.
      do
        voucher_status := a_name
      ensure
        voucher_status_set: voucher_status = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass QUOTATION_CREATE%N")
        if attached address as l_address then
          Result.append ("%Naddress:")
          Result.append (l_address.out)
          Result.append ("%N")
        end
        if attached contact_id as l_contact_id then
          Result.append ("%Ncontact_id:")
          Result.append (l_contact_id.out)
          Result.append ("%N")
        end
        if attached contact_name as l_contact_name then
          Result.append ("%Ncontact_name:")
          Result.append (l_contact_name.out)
          Result.append ("%N")
        end
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached expiration_date as l_expiration_date then
          Result.append ("%Nexpiration_date:")
          Result.append (l_expiration_date.out)
          Result.append ("%N")
        end
        if attached files as l_files then
          Result.append ("%Nfiles:")
          Result.append (l_files.out)
          Result.append ("%N")
        end
        if attached introduction as l_introduction then
          Result.append ("%Nintroduction:")
          Result.append (l_introduction.out)
          Result.append ("%N")
        end
        if attached line_items as l_line_items then
          Result.append ("%Nline_items:")
          Result.append (l_line_items.out)
          Result.append ("%N")
        end
        if attached preceding_sales_voucher_id as l_preceding_sales_voucher_id then
          Result.append ("%Npreceding_sales_voucher_id:")
          Result.append (l_preceding_sales_voucher_id.out)
          Result.append ("%N")
        end
        if attached preceding_sales_voucher_type as l_preceding_sales_voucher_type then
          Result.append ("%Npreceding_sales_voucher_type:")
          Result.append (l_preceding_sales_voucher_type.out)
          Result.append ("%N")
        end
        if attached quotation_number as l_quotation_number then
          Result.append ("%Nquotation_number:")
          Result.append (l_quotation_number.out)
          Result.append ("%N")
        end
        if attached remark as l_remark then
          Result.append ("%Nremark:")
          Result.append (l_remark.out)
          Result.append ("%N")
        end
        if attached tax_condition as l_tax_condition then
          Result.append ("%Ntax_condition:")
          Result.append (l_tax_condition.out)
          Result.append ("%N")
        end
        if attached title as l_title then
          Result.append ("%Ntitle:")
          Result.append (l_title.out)
          Result.append ("%N")
        end
        if attached voucher_date as l_voucher_date then
          Result.append ("%Nvoucher_date:")
          Result.append (l_voucher_date.out)
          Result.append ("%N")
        end
        if attached voucher_status as l_voucher_status then
          Result.append ("%Nvoucher_status:")
          Result.append (l_voucher_status.out)
          Result.append ("%N")
        end
      end
end

