note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class QUOTA_OVERRIDE




feature --Access

    features: detachable QUOTA_OVERRIDE_FEATURES
      
    max_connectors: INTEGER_32
      
    max_invoices_per_month: INTEGER_64
      
    max_users: INTEGER_32
      
    metered: detachable STRING_TABLE [INTEGER_64]
      
    plan: detachable STRING_32
      -- Custom plan id; unknown ids resolve to enterprise limits.

feature -- Change Element

    set_features (a_name: like features)
        -- Set 'features' with 'a_name'.
      do
        features := a_name
      ensure
        features_set: features = a_name
      end

    set_max_connectors (a_name: like max_connectors)
        -- Set 'max_connectors' with 'a_name'.
      do
        max_connectors := a_name
      ensure
        max_connectors_set: max_connectors = a_name
      end

    set_max_invoices_per_month (a_name: like max_invoices_per_month)
        -- Set 'max_invoices_per_month' with 'a_name'.
      do
        max_invoices_per_month := a_name
      ensure
        max_invoices_per_month_set: max_invoices_per_month = a_name
      end

    set_max_users (a_name: like max_users)
        -- Set 'max_users' with 'a_name'.
      do
        max_users := a_name
      ensure
        max_users_set: max_users = a_name
      end

    set_metered (a_name: like metered)
        -- Set 'metered' with 'a_name'.
      do
        metered := a_name
      ensure
        metered_set: metered = a_name
      end

    set_plan (a_name: like plan)
        -- Set 'plan' with 'a_name'.
      do
        plan := a_name
      ensure
        plan_set: plan = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass QUOTA_OVERRIDE%N")
        if attached features as l_features then
          Result.append ("%Nfeatures:")
          Result.append (l_features.out)
          Result.append ("%N")
        end
        if attached max_connectors as l_max_connectors then
          Result.append ("%Nmax_connectors:")
          Result.append (l_max_connectors.out)
          Result.append ("%N")
        end
        if attached max_invoices_per_month as l_max_invoices_per_month then
          Result.append ("%Nmax_invoices_per_month:")
          Result.append (l_max_invoices_per_month.out)
          Result.append ("%N")
        end
        if attached max_users as l_max_users then
          Result.append ("%Nmax_users:")
          Result.append (l_max_users.out)
          Result.append ("%N")
        end
        if attached metered as l_metered then
          Result.append ("%Nmetered:")
          across l_metered as ic loop
            Result.append ("%N")
            Result.append ("key:")
            Result.append (ic.key.out)
            Result.append (" - ")
            Result.append ("val:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached plan as l_plan then
          Result.append ("%Nplan:")
          Result.append (l_plan.out)
          Result.append ("%N")
        end
      end
end

