note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class SALES_VOLUME_REPORT




feature --Access

    grand_total: detachable STRING_32
      
    items: detachable LIST [SALES_VOLUME_ITEM]
      
    total_count: INTEGER_64
      

feature -- Change Element

    set_grand_total (a_name: like grand_total)
        -- Set 'grand_total' with 'a_name'.
      do
        grand_total := a_name
      ensure
        grand_total_set: grand_total = a_name
      end

    set_items (a_name: like items)
        -- Set 'items' with 'a_name'.
      do
        items := a_name
      ensure
        items_set: items = a_name
      end

    set_total_count (a_name: like total_count)
        -- Set 'total_count' with 'a_name'.
      do
        total_count := a_name
      ensure
        total_count_set: total_count = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass SALES_VOLUME_REPORT%N")
        if attached grand_total as l_grand_total then
          Result.append ("%Ngrand_total:")
          Result.append (l_grand_total.out)
          Result.append ("%N")
        end
        if attached items as l_items then
          across l_items as ic loop
            Result.append ("%N items:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_count as l_total_count then
          Result.append ("%Ntotal_count:")
          Result.append (l_total_count.out)
          Result.append ("%N")
        end
      end
end

