note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class SERVICE_ASSIGNMENT_CREATE




feature --Access

    employee_id: detachable UUID
      -- References the employees entity.
    job_id: detachable UUID
      -- References the service_jobs entity.
    notes: detachable STRING_32
      
    scheduled_date: detachable DATE
      -- Work day the assignment is scheduled for.
    scheduled_end: detachable STRING_32
      -- Planned end time of the assignment.
    scheduled_start: detachable STRING_32
      -- Planned start time of the assignment.
    status: detachable SERVICE_ASSIGNMENT_STATUS
      -- Assignment lifecycle status: \"planned\", \"confirmed\", \"en_route\", \"in_progress\", \"completed\" or \"cancelled\".

feature -- Change Element

    set_employee_id (a_name: like employee_id)
        -- Set 'employee_id' with 'a_name'.
      do
        employee_id := a_name
      ensure
        employee_id_set: employee_id = a_name
      end

    set_job_id (a_name: like job_id)
        -- Set 'job_id' with 'a_name'.
      do
        job_id := a_name
      ensure
        job_id_set: job_id = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_scheduled_date (a_name: like scheduled_date)
        -- Set 'scheduled_date' with 'a_name'.
      do
        scheduled_date := a_name
      ensure
        scheduled_date_set: scheduled_date = a_name
      end

    set_scheduled_end (a_name: like scheduled_end)
        -- Set 'scheduled_end' with 'a_name'.
      do
        scheduled_end := a_name
      ensure
        scheduled_end_set: scheduled_end = a_name
      end

    set_scheduled_start (a_name: like scheduled_start)
        -- Set 'scheduled_start' with 'a_name'.
      do
        scheduled_start := a_name
      ensure
        scheduled_start_set: scheduled_start = a_name
      end

    set_status (a_name: like status)
        -- Set 'status' with 'a_name'.
      do
        status := a_name
      ensure
        status_set: status = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass SERVICE_ASSIGNMENT_CREATE%N")
        if attached employee_id as l_employee_id then
          Result.append ("%Nemployee_id:")
          Result.append (l_employee_id.out)
          Result.append ("%N")
        end
        if attached job_id as l_job_id then
          Result.append ("%Njob_id:")
          Result.append (l_job_id.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached scheduled_date as l_scheduled_date then
          Result.append ("%Nscheduled_date:")
          Result.append (l_scheduled_date.out)
          Result.append ("%N")
        end
        if attached scheduled_end as l_scheduled_end then
          Result.append ("%Nscheduled_end:")
          Result.append (l_scheduled_end.out)
          Result.append ("%N")
        end
        if attached scheduled_start as l_scheduled_start then
          Result.append ("%Nscheduled_start:")
          Result.append (l_scheduled_start.out)
          Result.append ("%N")
        end
        if attached status as l_status then
          Result.append ("%Nstatus:")
          Result.append (l_status.out)
          Result.append ("%N")
        end
      end
end

