note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class STILLE_REPORT




feature --Access

    jahresueberschuss: detachable STRING_32
      
    partners: detachable LIST [STILLE_PARTNER_ZEILE]
      
    year: INTEGER_32
      

feature -- Change Element

    set_jahresueberschuss (a_name: like jahresueberschuss)
        -- Set 'jahresueberschuss' with 'a_name'.
      do
        jahresueberschuss := a_name
      ensure
        jahresueberschuss_set: jahresueberschuss = a_name
      end

    set_partners (a_name: like partners)
        -- Set 'partners' with 'a_name'.
      do
        partners := a_name
      ensure
        partners_set: partners = a_name
      end

    set_year (a_name: like year)
        -- Set 'year' with 'a_name'.
      do
        year := a_name
      ensure
        year_set: year = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass STILLE_REPORT%N")
        if attached jahresueberschuss as l_jahresueberschuss then
          Result.append ("%Njahresueberschuss:")
          Result.append (l_jahresueberschuss.out)
          Result.append ("%N")
        end
        if attached partners as l_partners then
          across l_partners as ic loop
            Result.append ("%N partners:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached year as l_year then
          Result.append ("%Nyear:")
          Result.append (l_year.out)
          Result.append ("%N")
        end
      end
end

