note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class STOCK_ADJUSTMENT




feature --Access

    batch_number: detachable STRING_32
      
    bin_location: detachable STRING_32
      
    expiry_date: detachable DATE
      
    product_id: detachable UUID
      
    quantity: INTEGER_64
      
    serial_numbers: detachable LIST [STRING_32]
      

feature -- Change Element

    set_batch_number (a_name: like batch_number)
        -- Set 'batch_number' with 'a_name'.
      do
        batch_number := a_name
      ensure
        batch_number_set: batch_number = a_name
      end

    set_bin_location (a_name: like bin_location)
        -- Set 'bin_location' with 'a_name'.
      do
        bin_location := a_name
      ensure
        bin_location_set: bin_location = a_name
      end

    set_expiry_date (a_name: like expiry_date)
        -- Set 'expiry_date' with 'a_name'.
      do
        expiry_date := a_name
      ensure
        expiry_date_set: expiry_date = a_name
      end

    set_product_id (a_name: like product_id)
        -- Set 'product_id' with 'a_name'.
      do
        product_id := a_name
      ensure
        product_id_set: product_id = a_name
      end

    set_quantity (a_name: like quantity)
        -- Set 'quantity' with 'a_name'.
      do
        quantity := a_name
      ensure
        quantity_set: quantity = a_name
      end

    set_serial_numbers (a_name: like serial_numbers)
        -- Set 'serial_numbers' with 'a_name'.
      do
        serial_numbers := a_name
      ensure
        serial_numbers_set: serial_numbers = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass STOCK_ADJUSTMENT%N")
        if attached batch_number as l_batch_number then
          Result.append ("%Nbatch_number:")
          Result.append (l_batch_number.out)
          Result.append ("%N")
        end
        if attached bin_location as l_bin_location then
          Result.append ("%Nbin_location:")
          Result.append (l_bin_location.out)
          Result.append ("%N")
        end
        if attached expiry_date as l_expiry_date then
          Result.append ("%Nexpiry_date:")
          Result.append (l_expiry_date.out)
          Result.append ("%N")
        end
        if attached product_id as l_product_id then
          Result.append ("%Nproduct_id:")
          Result.append (l_product_id.out)
          Result.append ("%N")
        end
        if attached quantity as l_quantity then
          Result.append ("%Nquantity:")
          Result.append (l_quantity.out)
          Result.append ("%N")
        end
        if attached serial_numbers as l_serial_numbers then
          across l_serial_numbers as ic loop
            Result.append ("%N serial_numbers:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
      end
end

