note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class SUPPLIER_INVOICE_CREATE




feature --Access

    currency: detachable STRING_32
      
    goods_receipt_id: detachable STRING_32
      -- References the goods receipt entity.
    invoice_date: detachable DATE
      
    invoice_number: detachable STRING_32
      
    line_items: detachable ANY
      -- JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`.
    notes: detachable STRING_32
      
    purchase_order_id: detachable STRING_32
      -- References the purchase order entity.
    status: detachable SUPPLIER_INVOICE_STATUS
      -- One of: draft | matched | has_variances | posted | cancelled
    supplier_contact_id: detachable STRING_32
      -- References the supplier entity.
    supplier_name: detachable STRING_32
      
    total_gross_amount: detachable STRING_32
      
    total_net_amount: detachable STRING_32
      

feature -- Change Element

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_goods_receipt_id (a_name: like goods_receipt_id)
        -- Set 'goods_receipt_id' with 'a_name'.
      do
        goods_receipt_id := a_name
      ensure
        goods_receipt_id_set: goods_receipt_id = a_name
      end

    set_invoice_date (a_name: like invoice_date)
        -- Set 'invoice_date' with 'a_name'.
      do
        invoice_date := a_name
      ensure
        invoice_date_set: invoice_date = a_name
      end

    set_invoice_number (a_name: like invoice_number)
        -- Set 'invoice_number' with 'a_name'.
      do
        invoice_number := a_name
      ensure
        invoice_number_set: invoice_number = a_name
      end

    set_line_items (a_name: like line_items)
        -- Set 'line_items' with 'a_name'.
      do
        line_items := a_name
      ensure
        line_items_set: line_items = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_purchase_order_id (a_name: like purchase_order_id)
        -- Set 'purchase_order_id' with 'a_name'.
      do
        purchase_order_id := a_name
      ensure
        purchase_order_id_set: purchase_order_id = a_name
      end

    set_status (a_name: like status)
        -- Set 'status' with 'a_name'.
      do
        status := a_name
      ensure
        status_set: status = a_name
      end

    set_supplier_contact_id (a_name: like supplier_contact_id)
        -- Set 'supplier_contact_id' with 'a_name'.
      do
        supplier_contact_id := a_name
      ensure
        supplier_contact_id_set: supplier_contact_id = a_name
      end

    set_supplier_name (a_name: like supplier_name)
        -- Set 'supplier_name' with 'a_name'.
      do
        supplier_name := a_name
      ensure
        supplier_name_set: supplier_name = a_name
      end

    set_total_gross_amount (a_name: like total_gross_amount)
        -- Set 'total_gross_amount' with 'a_name'.
      do
        total_gross_amount := a_name
      ensure
        total_gross_amount_set: total_gross_amount = a_name
      end

    set_total_net_amount (a_name: like total_net_amount)
        -- Set 'total_net_amount' with 'a_name'.
      do
        total_net_amount := a_name
      ensure
        total_net_amount_set: total_net_amount = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass SUPPLIER_INVOICE_CREATE%N")
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached goods_receipt_id as l_goods_receipt_id then
          Result.append ("%Ngoods_receipt_id:")
          Result.append (l_goods_receipt_id.out)
          Result.append ("%N")
        end
        if attached invoice_date as l_invoice_date then
          Result.append ("%Ninvoice_date:")
          Result.append (l_invoice_date.out)
          Result.append ("%N")
        end
        if attached invoice_number as l_invoice_number then
          Result.append ("%Ninvoice_number:")
          Result.append (l_invoice_number.out)
          Result.append ("%N")
        end
        if attached line_items as l_line_items then
          Result.append ("%Nline_items:")
          Result.append (l_line_items.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached purchase_order_id as l_purchase_order_id then
          Result.append ("%Npurchase_order_id:")
          Result.append (l_purchase_order_id.out)
          Result.append ("%N")
        end
        if attached status as l_status then
          Result.append ("%Nstatus:")
          Result.append (l_status.out)
          Result.append ("%N")
        end
        if attached supplier_contact_id as l_supplier_contact_id then
          Result.append ("%Nsupplier_contact_id:")
          Result.append (l_supplier_contact_id.out)
          Result.append ("%N")
        end
        if attached supplier_name as l_supplier_name then
          Result.append ("%Nsupplier_name:")
          Result.append (l_supplier_name.out)
          Result.append ("%N")
        end
        if attached total_gross_amount as l_total_gross_amount then
          Result.append ("%Ntotal_gross_amount:")
          Result.append (l_total_gross_amount.out)
          Result.append ("%N")
        end
        if attached total_net_amount as l_total_net_amount then
          Result.append ("%Ntotal_net_amount:")
          Result.append (l_total_net_amount.out)
          Result.append ("%N")
        end
      end
end

