note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class TAX_RATE_CREATE




feature --Access

    country_code: detachable STRING_32
      -- ISO 3166-1 alpha-2 country code.
    effective_from: detachable DATE
      -- Date this rate took effect; `None` = not date-bound.
    is_default: BOOLEAN
      -- Default rate for the country (one per country); fallback for lookups when no dated rate applies.
    name: detachable STRING_32
      -- Human name, e.g. \"VAT\".
    rate_percent: INTEGER_64
      -- Rate in hundredths of a percent: 1900 = 19.00%.

feature -- Change Element

    set_country_code (a_name: like country_code)
        -- Set 'country_code' with 'a_name'.
      do
        country_code := a_name
      ensure
        country_code_set: country_code = a_name
      end

    set_effective_from (a_name: like effective_from)
        -- Set 'effective_from' with 'a_name'.
      do
        effective_from := a_name
      ensure
        effective_from_set: effective_from = a_name
      end

    set_is_default (a_name: like is_default)
        -- Set 'is_default' with 'a_name'.
      do
        is_default := a_name
      ensure
        is_default_set: is_default = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end

    set_rate_percent (a_name: like rate_percent)
        -- Set 'rate_percent' with 'a_name'.
      do
        rate_percent := a_name
      ensure
        rate_percent_set: rate_percent = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass TAX_RATE_CREATE%N")
        if attached country_code as l_country_code then
          Result.append ("%Ncountry_code:")
          Result.append (l_country_code.out)
          Result.append ("%N")
        end
        if attached effective_from as l_effective_from then
          Result.append ("%Neffective_from:")
          Result.append (l_effective_from.out)
          Result.append ("%N")
        end
        if attached is_default as l_is_default then
          Result.append ("%Nis_default:")
          Result.append (l_is_default.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
        if attached rate_percent as l_rate_percent then
          Result.append ("%Nrate_percent:")
          Result.append (l_rate_percent.out)
          Result.append ("%N")
        end
      end
end

