note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class TEAM




feature --Access

    created_at: detachable DATE_TIME
      
    description: detachable STRING_32
      
    id: detachable UUID
      
    name: detachable STRING_32
      
    parent_team_id: detachable UUID
      
    tenant_id: detachable UUID
      
    updated_at: detachable DATE_TIME
      

feature -- Change Element

    set_created_at (a_name: like created_at)
        -- Set 'created_at' with 'a_name'.
      do
        created_at := a_name
      ensure
        created_at_set: created_at = a_name
      end

    set_description (a_name: like description)
        -- Set 'description' with 'a_name'.
      do
        description := a_name
      ensure
        description_set: description = a_name
      end

    set_id (a_name: like id)
        -- Set 'id' with 'a_name'.
      do
        id := a_name
      ensure
        id_set: id = a_name
      end

    set_name (a_name: like name)
        -- Set 'name' with 'a_name'.
      do
        name := a_name
      ensure
        name_set: name = a_name
      end

    set_parent_team_id (a_name: like parent_team_id)
        -- Set 'parent_team_id' with 'a_name'.
      do
        parent_team_id := a_name
      ensure
        parent_team_id_set: parent_team_id = a_name
      end

    set_tenant_id (a_name: like tenant_id)
        -- Set 'tenant_id' with 'a_name'.
      do
        tenant_id := a_name
      ensure
        tenant_id_set: tenant_id = a_name
      end

    set_updated_at (a_name: like updated_at)
        -- Set 'updated_at' with 'a_name'.
      do
        updated_at := a_name
      ensure
        updated_at_set: updated_at = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass TEAM%N")
        if attached created_at as l_created_at then
          Result.append ("%Ncreated_at:")
          Result.append (l_created_at.out)
          Result.append ("%N")
        end
        if attached description as l_description then
          Result.append ("%Ndescription:")
          Result.append (l_description.out)
          Result.append ("%N")
        end
        if attached id as l_id then
          Result.append ("%Nid:")
          Result.append (l_id.out)
          Result.append ("%N")
        end
        if attached name as l_name then
          Result.append ("%Nname:")
          Result.append (l_name.out)
          Result.append ("%N")
        end
        if attached parent_team_id as l_parent_team_id then
          Result.append ("%Nparent_team_id:")
          Result.append (l_parent_team_id.out)
          Result.append ("%N")
        end
        if attached tenant_id as l_tenant_id then
          Result.append ("%Ntenant_id:")
          Result.append (l_tenant_id.out)
          Result.append ("%N")
        end
        if attached updated_at as l_updated_at then
          Result.append ("%Nupdated_at:")
          Result.append (l_updated_at.out)
          Result.append ("%N")
        end
      end
end

