note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class TICKET_MESSAGE




feature --Access

    author_email: detachable STRING_32
      
    author_name: detachable STRING_32
      
    body: detachable STRING_32
      
    body_html: detachable STRING_32
      
    channel_id: detachable UUID
      
    created_at: detachable DATE_TIME
      
    direction: detachable MESSAGE_DIRECTION
      
    external_id: detachable STRING_32
      
    is_internal: BOOLEAN
      
    message_type: detachable MESSAGE_TYPE
      
    metadata: detachable ANY
      
    tenant_id: detachable UUID
      
    ticket_id: detachable UUID
      -- References the ticket entity.

feature -- Change Element

    set_author_email (a_name: like author_email)
        -- Set 'author_email' with 'a_name'.
      do
        author_email := a_name
      ensure
        author_email_set: author_email = a_name
      end

    set_author_name (a_name: like author_name)
        -- Set 'author_name' with 'a_name'.
      do
        author_name := a_name
      ensure
        author_name_set: author_name = a_name
      end

    set_body (a_name: like body)
        -- Set 'body' with 'a_name'.
      do
        body := a_name
      ensure
        body_set: body = a_name
      end

    set_body_html (a_name: like body_html)
        -- Set 'body_html' with 'a_name'.
      do
        body_html := a_name
      ensure
        body_html_set: body_html = a_name
      end

    set_channel_id (a_name: like channel_id)
        -- Set 'channel_id' with 'a_name'.
      do
        channel_id := a_name
      ensure
        channel_id_set: channel_id = a_name
      end

    set_created_at (a_name: like created_at)
        -- Set 'created_at' with 'a_name'.
      do
        created_at := a_name
      ensure
        created_at_set: created_at = a_name
      end

    set_direction (a_name: like direction)
        -- Set 'direction' with 'a_name'.
      do
        direction := a_name
      ensure
        direction_set: direction = a_name
      end

    set_external_id (a_name: like external_id)
        -- Set 'external_id' with 'a_name'.
      do
        external_id := a_name
      ensure
        external_id_set: external_id = a_name
      end

    set_is_internal (a_name: like is_internal)
        -- Set 'is_internal' with 'a_name'.
      do
        is_internal := a_name
      ensure
        is_internal_set: is_internal = a_name
      end

    set_message_type (a_name: like message_type)
        -- Set 'message_type' with 'a_name'.
      do
        message_type := a_name
      ensure
        message_type_set: message_type = a_name
      end

    set_metadata (a_name: like metadata)
        -- Set 'metadata' with 'a_name'.
      do
        metadata := a_name
      ensure
        metadata_set: metadata = a_name
      end

    set_tenant_id (a_name: like tenant_id)
        -- Set 'tenant_id' with 'a_name'.
      do
        tenant_id := a_name
      ensure
        tenant_id_set: tenant_id = a_name
      end

    set_ticket_id (a_name: like ticket_id)
        -- Set 'ticket_id' with 'a_name'.
      do
        ticket_id := a_name
      ensure
        ticket_id_set: ticket_id = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass TICKET_MESSAGE%N")
        if attached author_email as l_author_email then
          Result.append ("%Nauthor_email:")
          Result.append (l_author_email.out)
          Result.append ("%N")
        end
        if attached author_name as l_author_name then
          Result.append ("%Nauthor_name:")
          Result.append (l_author_name.out)
          Result.append ("%N")
        end
        if attached body as l_body then
          Result.append ("%Nbody:")
          Result.append (l_body.out)
          Result.append ("%N")
        end
        if attached body_html as l_body_html then
          Result.append ("%Nbody_html:")
          Result.append (l_body_html.out)
          Result.append ("%N")
        end
        if attached channel_id as l_channel_id then
          Result.append ("%Nchannel_id:")
          Result.append (l_channel_id.out)
          Result.append ("%N")
        end
        if attached created_at as l_created_at then
          Result.append ("%Ncreated_at:")
          Result.append (l_created_at.out)
          Result.append ("%N")
        end
        if attached direction as l_direction then
          Result.append ("%Ndirection:")
          Result.append (l_direction.out)
          Result.append ("%N")
        end
        if attached external_id as l_external_id then
          Result.append ("%Nexternal_id:")
          Result.append (l_external_id.out)
          Result.append ("%N")
        end
        if attached is_internal as l_is_internal then
          Result.append ("%Nis_internal:")
          Result.append (l_is_internal.out)
          Result.append ("%N")
        end
        if attached message_type as l_message_type then
          Result.append ("%Nmessage_type:")
          Result.append (l_message_type.out)
          Result.append ("%N")
        end
        if attached metadata as l_metadata then
          Result.append ("%Nmetadata:")
          Result.append (l_metadata.out)
          Result.append ("%N")
        end
        if attached tenant_id as l_tenant_id then
          Result.append ("%Ntenant_id:")
          Result.append (l_tenant_id.out)
          Result.append ("%N")
        end
        if attached ticket_id as l_ticket_id then
          Result.append ("%Nticket_id:")
          Result.append (l_ticket_id.out)
          Result.append ("%N")
        end
      end
end

