note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class TRAINING_CONTENT




feature --Access

    code: detachable STRING_32
      
    contact: detachable CONTACT_INFO
      
    pass_score: INTEGER_32
      
    quiz: detachable LIST [QUIZ_QUESTION]
      
    sections: detachable LIST [SECTION]
      
    title: detachable STRING_32
      
    title_en: detachable STRING_32
      

feature -- Change Element

    set_code (a_name: like code)
        -- Set 'code' with 'a_name'.
      do
        code := a_name
      ensure
        code_set: code = a_name
      end

    set_contact (a_name: like contact)
        -- Set 'contact' with 'a_name'.
      do
        contact := a_name
      ensure
        contact_set: contact = a_name
      end

    set_pass_score (a_name: like pass_score)
        -- Set 'pass_score' with 'a_name'.
      do
        pass_score := a_name
      ensure
        pass_score_set: pass_score = a_name
      end

    set_quiz (a_name: like quiz)
        -- Set 'quiz' with 'a_name'.
      do
        quiz := a_name
      ensure
        quiz_set: quiz = a_name
      end

    set_sections (a_name: like sections)
        -- Set 'sections' with 'a_name'.
      do
        sections := a_name
      ensure
        sections_set: sections = a_name
      end

    set_title (a_name: like title)
        -- Set 'title' with 'a_name'.
      do
        title := a_name
      ensure
        title_set: title = a_name
      end

    set_title_en (a_name: like title_en)
        -- Set 'title_en' with 'a_name'.
      do
        title_en := a_name
      ensure
        title_en_set: title_en = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass TRAINING_CONTENT%N")
        if attached code as l_code then
          Result.append ("%Ncode:")
          Result.append (l_code.out)
          Result.append ("%N")
        end
        if attached contact as l_contact then
          Result.append ("%Ncontact:")
          Result.append (l_contact.out)
          Result.append ("%N")
        end
        if attached pass_score as l_pass_score then
          Result.append ("%Npass_score:")
          Result.append (l_pass_score.out)
          Result.append ("%N")
        end
        if attached quiz as l_quiz then
          across l_quiz as ic loop
            Result.append ("%N quiz:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached sections as l_sections then
          across l_sections as ic loop
            Result.append ("%N sections:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached title as l_title then
          Result.append ("%Ntitle:")
          Result.append (l_title.out)
          Result.append ("%N")
        end
        if attached title_en as l_title_en then
          Result.append ("%Ntitle_en:")
          Result.append (l_title_en.out)
          Result.append ("%N")
        end
      end
end

