note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class VAT_ITEM




feature --Access

    net_amount: detachable STRING_32
      
    tax_amount: detachable STRING_32
      
    tax_rate: detachable STRING_32
      

feature -- Change Element

    set_net_amount (a_name: like net_amount)
        -- Set 'net_amount' with 'a_name'.
      do
        net_amount := a_name
      ensure
        net_amount_set: net_amount = a_name
      end

    set_tax_amount (a_name: like tax_amount)
        -- Set 'tax_amount' with 'a_name'.
      do
        tax_amount := a_name
      ensure
        tax_amount_set: tax_amount = a_name
      end

    set_tax_rate (a_name: like tax_rate)
        -- Set 'tax_rate' with 'a_name'.
      do
        tax_rate := a_name
      ensure
        tax_rate_set: tax_rate = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass VAT_ITEM%N")
        if attached net_amount as l_net_amount then
          Result.append ("%Nnet_amount:")
          Result.append (l_net_amount.out)
          Result.append ("%N")
        end
        if attached tax_amount as l_tax_amount then
          Result.append ("%Ntax_amount:")
          Result.append (l_tax_amount.out)
          Result.append ("%N")
        end
        if attached tax_rate as l_tax_rate then
          Result.append ("%Ntax_rate:")
          Result.append (l_tax_rate.out)
          Result.append ("%N")
        end
      end
end

