note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class VAT_SUMMARY




feature --Access

    input_tax_items: detachable LIST [VAT_ITEM]
      
    output_tax_items: detachable LIST [VAT_ITEM]
      
    total_input_tax: detachable STRING_32
      
    total_output_tax: detachable STRING_32
      
    vat_due: detachable STRING_32
      

feature -- Change Element

    set_input_tax_items (a_name: like input_tax_items)
        -- Set 'input_tax_items' with 'a_name'.
      do
        input_tax_items := a_name
      ensure
        input_tax_items_set: input_tax_items = a_name
      end

    set_output_tax_items (a_name: like output_tax_items)
        -- Set 'output_tax_items' with 'a_name'.
      do
        output_tax_items := a_name
      ensure
        output_tax_items_set: output_tax_items = a_name
      end

    set_total_input_tax (a_name: like total_input_tax)
        -- Set 'total_input_tax' with 'a_name'.
      do
        total_input_tax := a_name
      ensure
        total_input_tax_set: total_input_tax = a_name
      end

    set_total_output_tax (a_name: like total_output_tax)
        -- Set 'total_output_tax' with 'a_name'.
      do
        total_output_tax := a_name
      ensure
        total_output_tax_set: total_output_tax = a_name
      end

    set_vat_due (a_name: like vat_due)
        -- Set 'vat_due' with 'a_name'.
      do
        vat_due := a_name
      ensure
        vat_due_set: vat_due = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass VAT_SUMMARY%N")
        if attached input_tax_items as l_input_tax_items then
          across l_input_tax_items as ic loop
            Result.append ("%N input_tax_items:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached output_tax_items as l_output_tax_items then
          across l_output_tax_items as ic loop
            Result.append ("%N output_tax_items:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end
        if attached total_input_tax as l_total_input_tax then
          Result.append ("%Ntotal_input_tax:")
          Result.append (l_total_input_tax.out)
          Result.append ("%N")
        end
        if attached total_output_tax as l_total_output_tax then
          Result.append ("%Ntotal_output_tax:")
          Result.append (l_total_output_tax.out)
          Result.append ("%N")
        end
        if attached vat_due as l_vat_due then
          Result.append ("%Nvat_due:")
          Result.append (l_vat_due.out)
          Result.append ("%N")
        end
      end
end

