note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class VOUCHER_CREATE




feature --Access

    category_id: detachable STRING_32
      
    contact_id: detachable STRING_32
      -- References the contact entity.
    contact_name: detachable STRING_32
      
    currency: detachable STRING_32
      
    description: detachable STRING_32
      
    file_attachments: detachable ANY
      
    line_items: detachable ANY
      
    metadata: detachable ANY
      
    notes: detachable STRING_32
      
    open_amount: detachable STRING_32
      
    paid_date: detachable DATE
      
    payment_status: detachable PAYMENT_STATUS
      
    tax_amounts: detachable ANY
      
    tax_condition: detachable STRING_32
      
    total_gross_amount: detachable STRING_32
      
    total_net_amount: detachable STRING_32
      
    voucher_date: detachable DATE
      
    voucher_number: detachable STRING_32
      
    voucher_status: detachable VOUCHER_STATUS
      
    voucher_type: detachable VOUCHER_TYPE
      

feature -- Change Element

    set_category_id (a_name: like category_id)
        -- Set 'category_id' with 'a_name'.
      do
        category_id := a_name
      ensure
        category_id_set: category_id = a_name
      end

    set_contact_id (a_name: like contact_id)
        -- Set 'contact_id' with 'a_name'.
      do
        contact_id := a_name
      ensure
        contact_id_set: contact_id = a_name
      end

    set_contact_name (a_name: like contact_name)
        -- Set 'contact_name' with 'a_name'.
      do
        contact_name := a_name
      ensure
        contact_name_set: contact_name = a_name
      end

    set_currency (a_name: like currency)
        -- Set 'currency' with 'a_name'.
      do
        currency := a_name
      ensure
        currency_set: currency = a_name
      end

    set_description (a_name: like description)
        -- Set 'description' with 'a_name'.
      do
        description := a_name
      ensure
        description_set: description = a_name
      end

    set_file_attachments (a_name: like file_attachments)
        -- Set 'file_attachments' with 'a_name'.
      do
        file_attachments := a_name
      ensure
        file_attachments_set: file_attachments = a_name
      end

    set_line_items (a_name: like line_items)
        -- Set 'line_items' with 'a_name'.
      do
        line_items := a_name
      ensure
        line_items_set: line_items = a_name
      end

    set_metadata (a_name: like metadata)
        -- Set 'metadata' with 'a_name'.
      do
        metadata := a_name
      ensure
        metadata_set: metadata = a_name
      end

    set_notes (a_name: like notes)
        -- Set 'notes' with 'a_name'.
      do
        notes := a_name
      ensure
        notes_set: notes = a_name
      end

    set_open_amount (a_name: like open_amount)
        -- Set 'open_amount' with 'a_name'.
      do
        open_amount := a_name
      ensure
        open_amount_set: open_amount = a_name
      end

    set_paid_date (a_name: like paid_date)
        -- Set 'paid_date' with 'a_name'.
      do
        paid_date := a_name
      ensure
        paid_date_set: paid_date = a_name
      end

    set_payment_status (a_name: like payment_status)
        -- Set 'payment_status' with 'a_name'.
      do
        payment_status := a_name
      ensure
        payment_status_set: payment_status = a_name
      end

    set_tax_amounts (a_name: like tax_amounts)
        -- Set 'tax_amounts' with 'a_name'.
      do
        tax_amounts := a_name
      ensure
        tax_amounts_set: tax_amounts = a_name
      end

    set_tax_condition (a_name: like tax_condition)
        -- Set 'tax_condition' with 'a_name'.
      do
        tax_condition := a_name
      ensure
        tax_condition_set: tax_condition = a_name
      end

    set_total_gross_amount (a_name: like total_gross_amount)
        -- Set 'total_gross_amount' with 'a_name'.
      do
        total_gross_amount := a_name
      ensure
        total_gross_amount_set: total_gross_amount = a_name
      end

    set_total_net_amount (a_name: like total_net_amount)
        -- Set 'total_net_amount' with 'a_name'.
      do
        total_net_amount := a_name
      ensure
        total_net_amount_set: total_net_amount = a_name
      end

    set_voucher_date (a_name: like voucher_date)
        -- Set 'voucher_date' with 'a_name'.
      do
        voucher_date := a_name
      ensure
        voucher_date_set: voucher_date = a_name
      end

    set_voucher_number (a_name: like voucher_number)
        -- Set 'voucher_number' with 'a_name'.
      do
        voucher_number := a_name
      ensure
        voucher_number_set: voucher_number = a_name
      end

    set_voucher_status (a_name: like voucher_status)
        -- Set 'voucher_status' with 'a_name'.
      do
        voucher_status := a_name
      ensure
        voucher_status_set: voucher_status = a_name
      end

    set_voucher_type (a_name: like voucher_type)
        -- Set 'voucher_type' with 'a_name'.
      do
        voucher_type := a_name
      ensure
        voucher_type_set: voucher_type = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass VOUCHER_CREATE%N")
        if attached category_id as l_category_id then
          Result.append ("%Ncategory_id:")
          Result.append (l_category_id.out)
          Result.append ("%N")
        end
        if attached contact_id as l_contact_id then
          Result.append ("%Ncontact_id:")
          Result.append (l_contact_id.out)
          Result.append ("%N")
        end
        if attached contact_name as l_contact_name then
          Result.append ("%Ncontact_name:")
          Result.append (l_contact_name.out)
          Result.append ("%N")
        end
        if attached currency as l_currency then
          Result.append ("%Ncurrency:")
          Result.append (l_currency.out)
          Result.append ("%N")
        end
        if attached description as l_description then
          Result.append ("%Ndescription:")
          Result.append (l_description.out)
          Result.append ("%N")
        end
        if attached file_attachments as l_file_attachments then
          Result.append ("%Nfile_attachments:")
          Result.append (l_file_attachments.out)
          Result.append ("%N")
        end
        if attached line_items as l_line_items then
          Result.append ("%Nline_items:")
          Result.append (l_line_items.out)
          Result.append ("%N")
        end
        if attached metadata as l_metadata then
          Result.append ("%Nmetadata:")
          Result.append (l_metadata.out)
          Result.append ("%N")
        end
        if attached notes as l_notes then
          Result.append ("%Nnotes:")
          Result.append (l_notes.out)
          Result.append ("%N")
        end
        if attached open_amount as l_open_amount then
          Result.append ("%Nopen_amount:")
          Result.append (l_open_amount.out)
          Result.append ("%N")
        end
        if attached paid_date as l_paid_date then
          Result.append ("%Npaid_date:")
          Result.append (l_paid_date.out)
          Result.append ("%N")
        end
        if attached payment_status as l_payment_status then
          Result.append ("%Npayment_status:")
          Result.append (l_payment_status.out)
          Result.append ("%N")
        end
        if attached tax_amounts as l_tax_amounts then
          Result.append ("%Ntax_amounts:")
          Result.append (l_tax_amounts.out)
          Result.append ("%N")
        end
        if attached tax_condition as l_tax_condition then
          Result.append ("%Ntax_condition:")
          Result.append (l_tax_condition.out)
          Result.append ("%N")
        end
        if attached total_gross_amount as l_total_gross_amount then
          Result.append ("%Ntotal_gross_amount:")
          Result.append (l_total_gross_amount.out)
          Result.append ("%N")
        end
        if attached total_net_amount as l_total_net_amount then
          Result.append ("%Ntotal_net_amount:")
          Result.append (l_total_net_amount.out)
          Result.append ("%N")
        end
        if attached voucher_date as l_voucher_date then
          Result.append ("%Nvoucher_date:")
          Result.append (l_voucher_date.out)
          Result.append ("%N")
        end
        if attached voucher_number as l_voucher_number then
          Result.append ("%Nvoucher_number:")
          Result.append (l_voucher_number.out)
          Result.append ("%N")
        end
        if attached voucher_status as l_voucher_status then
          Result.append ("%Nvoucher_status:")
          Result.append (l_voucher_status.out)
          Result.append ("%N")
        end
        if attached voucher_type as l_voucher_type then
          Result.append ("%Nvoucher_type:")
          Result.append (l_voucher_type.out)
          Result.append ("%N")
        end
      end
end

