note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class YEAR_TOTAL




feature --Access

    tco2e: detachable STRING_32
      
    year: INTEGER_32
      

feature -- Change Element

    set_tco2e (a_name: like tco2e)
        -- Set 'tco2e' with 'a_name'.
      do
        tco2e := a_name
      ensure
        tco2e_set: tco2e = a_name
      end

    set_year (a_name: like year)
        -- Set 'year' with 'a_name'.
      do
        year := a_name
      ensure
        year_set: year = a_name
      end


 feature -- Status Report

    output: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass YEAR_TOTAL%N")
        if attached tco2e as l_tco2e then
          Result.append ("%Ntco2e:")
          Result.append (l_tco2e.out)
          Result.append ("%N")
        end
        if attached year as l_year then
          Result.append ("%Nyear:")
          Result.append (l_year.out)
          Result.append ("%N")
        end
      end
end

