note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"

class
	GEZ_API

inherit

    API_I


feature -- API Access


	gez_api (jahr: INTEGER_32; betriebsstaetten: STRING_32; kfz: INTEGER_64; hotelzimmer: INTEGER_64; beschaefigte: INTEGER_64): detachable GEZ_REPORT
			-- 
			-- 
			-- 
			-- argument: jahr  (optional, default to null)
			-- 
			-- argument: betriebsstaetten Liste der Betriebsstätten als JSON, z.B. &#x60;[{\&quot;name\&quot;:\&quot;Filiale 1\&quot;,\&quot;beschaefigte\&quot;:12}]&#x60;. (optional, default to null)
			-- 
			-- argument: kfz Gesamtzahl der betrieblich genutzten Kfz (falls keine Betriebsstätten angegeben sind). (optional, default to null)
			-- 
			-- argument: hotelzimmer Gesamtzahl der Hotel-/Gästezimmer und Ferienwohnungen. (optional, default to null)
			-- 
			-- argument: beschaefigte Gesamtzahl der Beschäftigten (verwendet nur, wenn &#x60;betriebsstaetten&#x60; fehlt; dann wird eine einzelne Betriebsstätte angenommen). (optional, default to null)
			-- 
			-- 
			-- Result GEZ_REPORT
		require
     		kfz_is_greater_or_equal_than: kfz >= 0
     		hotelzimmer_is_greater_or_equal_than: hotelzimmer >= 0
     		beschaefigte_is_greater_or_equal_than: beschaefigte >= 0
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/bookkeeping/gez"
			l_request.fill_query_params(api_client.parameter_to_tuple("", "jahr", jahr));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "betriebsstaetten", betriebsstaetten));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "kfz", kfz));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "hotelzimmer", hotelzimmer));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "beschaefigte", beschaefigte));


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { GEZ_REPORT } l_response.data ({ GEZ_REPORT }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end


end
