note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"

class
	PRODUCTIONORDER_API

inherit

    API_I


feature -- API Access


	create_production_order (production_order: PRODUCTION_ORDER): detachable PRODUCTION_ORDER
			-- 
			-- 
			-- 
			-- argument: production_order  (required)
			-- 
			-- 
			-- Result PRODUCTION_ORDER
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(production_order)
			l_path := "/api/v1/production-orders"


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Post", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PRODUCTION_ORDER } l_response.data ({ PRODUCTION_ORDER }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	delete_production_order (production_order_id: UUID)
			-- 
			-- 
			-- 
			-- argument: production_order_id  (required)
			-- 
			-- 
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/production-orders/{production_order_id}"
			l_path.replace_substring_all ("{"+"production_order_id"+"}", api_client.url_encode (production_order_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Delete", l_request, agent serializer, Void)
			if l_response.has_error then
				last_error := l_response.error
			end
		end

	list_production_orders (page: INTEGER_32; page_size: INTEGER_32; search: STRING_32; status: STRING_32): detachable LIST [PRODUCTION_ORDER]
			-- 
			-- 
			-- 
			-- argument: page  (optional, default to null)
			-- 
			-- argument: page_size  (optional, default to null)
			-- 
			-- argument: search  (optional, default to null)
			-- 
			-- argument: status Filter by status. (optional, default to null)
			-- 
			-- 
			-- Result LIST [PRODUCTION_ORDER]
		require
     		page_is_greater_or_equal_than: page >= 0
     		page_size_is_greater_or_equal_than: page_size >= 0
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/production-orders/"
			l_request.fill_query_params(api_client.parameter_to_tuple("", "page", page));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "pageSize", page_size));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "search", search));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "status", status));


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { LIST [PRODUCTION_ORDER] } l_response.data ({ LIST [PRODUCTION_ORDER] }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	production_order (production_order_id: UUID): detachable PRODUCTION_ORDER
			-- 
			-- 
			-- 
			-- argument: production_order_id  (required)
			-- 
			-- 
			-- Result PRODUCTION_ORDER
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/production-orders/{production_order_id}"
			l_path.replace_substring_all ("{"+"production_order_id"+"}", api_client.url_encode (production_order_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PRODUCTION_ORDER } l_response.data ({ PRODUCTION_ORDER }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	production_order_costing (production_order_id: UUID): detachable PRODUCTION_ORDER_COSTING
			-- Actual-costing report (Nachkalkulation) — material costs from BOM components at their purchase price plus the resulting per-unit cost and margin against the finished product&#39;s sale price.
			-- 
			-- 
			-- argument: production_order_id  (required)
			-- 
			-- 
			-- Result PRODUCTION_ORDER_COSTING
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/production-orders/{production_order_id}/costing"
			l_path.replace_substring_all ("{"+"production_order_id"+"}", api_client.url_encode (production_order_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PRODUCTION_ORDER_COSTING } l_response.data ({ PRODUCTION_ORDER_COSTING }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	update_production_order (production_order_id: UUID; production_order: PRODUCTION_ORDER): detachable PRODUCTION_ORDER
			-- 
			-- 
			-- 
			-- argument: production_order_id  (required)
			-- 
			-- argument: production_order  (required)
			-- 
			-- 
			-- Result PRODUCTION_ORDER
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(production_order)
			l_path := "/api/v1/production-orders/{production_order_id}"
			l_path.replace_substring_all ("{"+"production_order_id"+"}", api_client.url_encode (production_order_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Put", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PRODUCTION_ORDER } l_response.data ({ PRODUCTION_ORDER }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	update_production_order_status (production_order_id: UUID; production_order_status_update: PRODUCTION_ORDER_STATUS_UPDATE): detachable PRODUCTION_ORDER
			-- 
			-- 
			-- 
			-- argument: production_order_id  (required)
			-- 
			-- argument: production_order_status_update  (required)
			-- 
			-- 
			-- Result PRODUCTION_ORDER
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(production_order_status_update)
			l_path := "/api/v1/production-orders/{production_order_id}/status"
			l_path.replace_substring_all ("{"+"production_order_id"+"}", api_client.url_encode (production_order_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Put", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PRODUCTION_ORDER } l_response.data ({ PRODUCTION_ORDER }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end


end
