note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"

class
	PROFORMAINVOICE_API

inherit

    API_I


feature -- API Access


	convert_proforma_to_invoice (proforma_id: STRING_32): detachable CONVERT_RESPONSE
			-- 
			-- 
			-- 
			-- argument: proforma_id  (required)
			-- 
			-- 
			-- Result CONVERT_RESPONSE
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/proforma-invoices/{proforma_id}/convert"
			l_path.replace_substring_all ("{"+"proforma_id"+"}", api_client.url_encode (proforma_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Post", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { CONVERT_RESPONSE } l_response.data ({ CONVERT_RESPONSE }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	create_proforma_invoice (proforma_invoice: PROFORMA_INVOICE): detachable PROFORMA_INVOICE
			-- 
			-- 
			-- 
			-- argument: proforma_invoice  (required)
			-- 
			-- 
			-- Result PROFORMA_INVOICE
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(proforma_invoice)
			l_path := "/api/v1/proforma-invoices"


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Post", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PROFORMA_INVOICE } l_response.data ({ PROFORMA_INVOICE }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	delete_proforma_invoice (proforma_id: STRING_32)
			-- 
			-- 
			-- 
			-- argument: proforma_id  (required)
			-- 
			-- 
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/proforma-invoices/{proforma_id}"
			l_path.replace_substring_all ("{"+"proforma_id"+"}", api_client.url_encode (proforma_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Delete", l_request, agent serializer, Void)
			if l_response.has_error then
				last_error := l_response.error
			end
		end

	list_proforma_invoices (page: INTEGER_32; page_size: INTEGER_32; status: STRING_32; customer_id: STRING_32; order_number: STRING_32): detachable LIST [PROFORMA_INVOICE]
			-- 
			-- 
			-- 
			-- argument: page  (optional, default to null)
			-- 
			-- argument: page_size  (optional, default to null)
			-- 
			-- argument: status  (optional, default to null)
			-- 
			-- argument: customer_id  (optional, default to null)
			-- 
			-- argument: order_number  (optional, default to null)
			-- 
			-- 
			-- Result LIST [PROFORMA_INVOICE]
		require
     		page_is_greater_or_equal_than: page >= 0
     		page_size_is_greater_or_equal_than: page_size >= 0
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/proforma-invoices/"
			l_request.fill_query_params(api_client.parameter_to_tuple("", "page", page));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "page_size", page_size));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "status", status));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "customer_id", customer_id));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "order_number", order_number));


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { LIST [PROFORMA_INVOICE] } l_response.data ({ LIST [PROFORMA_INVOICE] }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	proforma_invoice (proforma_id: STRING_32): detachable PROFORMA_INVOICE
			-- 
			-- 
			-- 
			-- argument: proforma_id  (required)
			-- 
			-- 
			-- Result PROFORMA_INVOICE
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/proforma-invoices/{proforma_id}"
			l_path.replace_substring_all ("{"+"proforma_id"+"}", api_client.url_encode (proforma_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PROFORMA_INVOICE } l_response.data ({ PROFORMA_INVOICE }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	update_proforma_invoice (proforma_id: STRING_32; body: ANY): detachable PROFORMA_INVOICE
			-- 
			-- 
			-- 
			-- argument: proforma_id  (required)
			-- 
			-- argument: body  (required)
			-- 
			-- 
			-- Result PROFORMA_INVOICE
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(body)
			l_path := "/api/v1/proforma-invoices/{proforma_id}"
			l_path.replace_substring_all ("{"+"proforma_id"+"}", api_client.url_encode (proforma_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Put", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { PROFORMA_INVOICE } l_response.data ({ PROFORMA_INVOICE }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end


end
