note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"

class
	SUPPLIERCONDITION_API

inherit

    API_I


feature -- API Access


	create_supplier_condition (supplier_condition_create: SUPPLIER_CONDITION_CREATE): detachable SUPPLIER_CONDITION
			-- 
			-- 
			-- 
			-- argument: supplier_condition_create  (required)
			-- 
			-- 
			-- Result SUPPLIER_CONDITION
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(supplier_condition_create)
			l_path := "/api/v1/supplier-conditions"


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Post", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { SUPPLIER_CONDITION } l_response.data ({ SUPPLIER_CONDITION }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	delete_supplier_condition (supplier_condition_id: STRING_32)
			-- 
			-- 
			-- 
			-- argument: supplier_condition_id  (required)
			-- 
			-- 
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/supplier-conditions/{supplier_condition_id}"
			l_path.replace_substring_all ("{"+"supplier_condition_id"+"}", api_client.url_encode (supplier_condition_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Delete", l_request, agent serializer, Void)
			if l_response.has_error then
				last_error := l_response.error
			end
		end

	list_supplier_conditions (page: INTEGER_32; page_size: INTEGER_32; supplier_contact_id: STRING_32; search: STRING_32): detachable LIST [SUPPLIER_CONDITION]
			-- 
			-- 
			-- 
			-- argument: page  (optional, default to null)
			-- 
			-- argument: page_size  (optional, default to null)
			-- 
			-- argument: supplier_contact_id  (optional, default to null)
			-- 
			-- argument: search  (optional, default to null)
			-- 
			-- 
			-- Result LIST [SUPPLIER_CONDITION]
		require
     		page_is_greater_or_equal_than: page >= 0
     		page_size_is_greater_or_equal_than: page_size >= 0
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/supplier-conditions/"
			l_request.fill_query_params(api_client.parameter_to_tuple("", "page", page));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "page_size", page_size));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_contact_id", supplier_contact_id));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "search", search));


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { LIST [SUPPLIER_CONDITION] } l_response.data ({ LIST [SUPPLIER_CONDITION] }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	supplier_condition (supplier_condition_id: STRING_32): detachable SUPPLIER_CONDITION
			-- 
			-- 
			-- 
			-- argument: supplier_condition_id  (required)
			-- 
			-- 
			-- Result SUPPLIER_CONDITION
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/supplier-conditions/{supplier_condition_id}"
			l_path.replace_substring_all ("{"+"supplier_condition_id"+"}", api_client.url_encode (supplier_condition_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { SUPPLIER_CONDITION } l_response.data ({ SUPPLIER_CONDITION }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end

	update_supplier_condition (supplier_condition_id: STRING_32; supplier_condition_update: SUPPLIER_CONDITION_UPDATE): detachable SUPPLIER_CONDITION
			-- 
			-- 
			-- 
			-- argument: supplier_condition_id  (required)
			-- 
			-- argument: supplier_condition_update  (required)
			-- 
			-- 
			-- Result SUPPLIER_CONDITION
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			l_request.set_body(supplier_condition_update)
			l_path := "/api/v1/supplier-conditions/{supplier_condition_id}"
			l_path.replace_substring_all ("{"+"supplier_condition_id"+"}", api_client.url_encode (supplier_condition_id.out))


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/json">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<"application/json">>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Put", l_request, Void, agent deserializer)
			if l_response.has_error then
				last_error := l_response.error
			elseif attached { SUPPLIER_CONDITION } l_response.data ({ SUPPLIER_CONDITION }) as l_data then
				Result := l_data
			else
				create last_error.make ("Unknown error: Status response [ " + l_response.status.out + "]")
			end
		end


end
