note
 description:"[
		SimpleBilly API
 		Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
  		The version of the OpenAPI document: 0.1.0
 	    Contact: support@simplebilly.com

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"

class
	ZUGFERD_API

inherit

    API_I


feature -- API Access


	generate_zugferd_api (id: STRING_32; supplier_name: STRING_32; supplier_street: STRING_32; supplier_city: STRING_32; supplier_zip: STRING_32; supplier_country: STRING_32; supplier_vat_id: STRING_32)
			-- 
			-- 
			-- 
			-- argument: id  (required)
			-- 
			-- argument: supplier_name  (optional, default to null)
			-- 
			-- argument: supplier_street  (optional, default to null)
			-- 
			-- argument: supplier_city  (optional, default to null)
			-- 
			-- argument: supplier_zip  (optional, default to null)
			-- 
			-- argument: supplier_country  (optional, default to null)
			-- 
			-- argument: supplier_vat_id  (optional, default to null)
			-- 
			-- 
		require
		local
  			l_path: STRING
  			l_request: API_CLIENT_REQUEST
  			l_response: API_CLIENT_RESPONSE
		do
			reset_error
			create l_request
			
			l_path := "/api/v1/invoices/{id}/zugferd"
			l_path.replace_substring_all ("{"+"id"+"}", api_client.url_encode (id.out))
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_name", supplier_name));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_street", supplier_street));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_city", supplier_city));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_zip", supplier_zip));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_country", supplier_country));
			l_request.fill_query_params(api_client.parameter_to_tuple("", "supplier_vat_id", supplier_vat_id));


			if attached {STRING} api_client.select_header_accept ({ARRAY [STRING]}<<"application/pdf">>)  as l_accept then
				l_request.add_header(l_accept,"Accept");
			end
			l_request.add_header(api_client.select_header_content_type ({ARRAY [STRING]}<<>>),"Content-Type")
			l_request.set_auth_names ({ARRAY [STRING]}<<"bearer_token">>)
			l_response := api_client.call_api (l_path, "Get", l_request, agent serializer, Void)
			if l_response.has_error then
				last_error := l_response.error
			end
		end


end
